### ISSUE TITLE
rpy2 cannot find utils and stats package 

### ISSUE THREAD

**Issue by elsiel23** [rpy2/rpy2#1005]
**Describe the issue or bug**

I'm using Docker to deploy an AWS Lambda Python function that uses rpy2 to call a R function. I'm installing r-base and rpy2 from conda-forge and all conda installs are done in the /miniconda3/ directory.

I can successfully build the docker file, but when I test the function, I run into the error below. I can't figure out why since I verified that the R stats and base packages are installed in the /lib directory.
```
{
el:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/task/lambda_handler.py", line 2, in <module>
    import rpy2.robjects as robjects
  File "/var/lang/lib/python3.10/site-packages/rpy2/robjects/__init__.py", line 19, in <module>
    import rpy2.robjects.functions
  File "/var/lang/lib/python3.10/site-packages/rpy2/robjects/functions.py", line 14, in <module>
    from rpy2.robjects.vectors import Vector
  File "/var/lang/lib/python3.10/site-packages/rpy2/robjects/vectors.py", line 34, in <module>
    utils_ri = baseenv_ri['as.environment'](
  File "/var/lang/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/var/lang/lib/python3.10/site-packages/rpy2/rinterface.py", line 817, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
[WARNING]	2023-03-13T08:34:51.558Z		R[write to console]: Warning messages:
[WARNING]	2023-03-13T08:34:51.559Z		R[write to console]: 1: system call failed: Cannot allocate memory 
[WARNING]	2023-03-13T08:34:51.560Z		R[write to console]: 2: system call failed: Cannot allocate memory 
OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘stats’ in options("defaultPackages") was not found 
[WARNING]	2023-03-13T08:35:35.053Z		R[write to console]: Error in .Primitive("as.environment")("package:utils") : 
no item called "package:utils" on the search list
[ERROR] RRuntimeError: Error in .Primitive("as.environment")("package:utils") : 
no item called "package:utils" on the search list
Traceback (most recent call last):
  File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/task/lambda_handler.py", line 2, in <module>
    import rpy2.robjects as robjects
  File "/var/lang/lib/python3.10/site-packages/rpy2/robjects/__init__.py", line 19, in <module>
    import rpy2.robjects.functions
  File "/var/lang/lib/python3.10/site-packages/rpy2/robjects/functions.py", line 14, in <module>
    from rpy2.robjects.vectors import Vector
  File "/var/lang/lib/python3.10/site-packages/rpy2/robjects/vectors.py", line 34, in <module>
    utils_ri = baseenv_ri['as.environment'](
  File "/var/lang/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/var/lang/lib/python3.10/site-packages/rpy2/rinterface.py", line 817, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
[WARNING]	2023-03-13T08:35:35.673Z		R[write to console]: Warning messages:
[WARNING]	2023-03-13T08:35:35.674Z		R[write to console]: 1: system call failed: Cannot allocate memory 
[WARNING]	2023-03-13T08:35:35.674Z		R[write to console]: 2: system call failed: Cannot allocate memory 
Memory Size: 128 MB	Max Memory Used: 58 MB	
```

**To Reproduce**

Dockerfile
https://github.com/OurPlanscape/Planscape/blob/main/src/planscape_r_conda/Dockerfile
```
FROM public.ecr.aws/lambda/python:latest

RUN yum update -y && yum install -y wget && yum clean all

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# -p is the directory to install into, -b to be able to run unattended
RUN bash Miniconda3-latest-Linux-x86_64.sh -p /miniconda3 -b
RUN rm Miniconda3-latest-Linux-x86_64.sh

# Required for R https://github.com/ContinuumIO/anaconda-issues/issues/11133
RUN yum install -y which
RUN yum -y install tar

# Required for forsys
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum -y install openssl-devel udunits2-devel

RUN yum -y install util-linux
ENV PATH=/miniconda3/bin:${PATH}
# /miniconda3/bin:/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
RUN echo $PATH
RUN conda init bash
RUN conda init zsh
RUN conda config --add channels conda-forge
RUN /miniconda3/bin/activate
RUN conda install -y -c conda-forge gdal poppler r r-base r-stringi r-units blas-devel udunits2 r-sf r-tidyverse r-rgeos r-roxygen2 r-rgdal r-extremes r-doparallel r-r.utils rpy2
RUN R -e "install.packages('remotes', repos='http://cran.rstudio.com/')"
RUN R -e "remotes::install_github('forsys-sp/forsysr', force=TRUE)"
RUN R -e "sessionInfo()"
RUN R -e ".libPaths()"

RUN ln -s /miniconda/bin/R /usr/bin/R
RUN ln -s /miniconda/lib/R /usr/lib/R

ENV LD_LIBRARY_PATH=/miniconda3/lib/R/lib:/miniconda3/lib/R/library:/usr/local/lib:${LD_LIBRARY_PATH}

# python: /usr/bin/python /usr/bin/python2.7 /usr/lib/python2.7 /usr/lib64/python2.7 /etc/python /usr/include/python2.7 /miniconda3/bin/python3.10-config /miniconda3/bin/python /miniconda3/bin/python3.10 /miniconda3/bin/python3.1 /var/lang/bin/python3.10-config /var/lang/bin/python /var/lang/bin/python3.10 /usr/share/man/man1/python.1.gz
RUN whereis python
RUN which python

# pip: /miniconda3/bin/pip /miniconda3/bin/pip3.10 /var/lang/bin/pip /var/lang/bin/pip3.10
# RUN whereis pip


# R: /miniconda3/bin/R
RUN whereis R
RUN which R

# Copy function code
COPY lambda_handler.py ${LAMBDA_TASK_ROOT}
COPY rank.R ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD ["lambda_handler.lambda_handler"]
```

**Expected behavior**
I should be able to run the Lambda function without any errors.

**Additional context**
```
Step 20/34 : RUN R -e "sessionInfo()"
 ---> Running in 6e44b00f71a3
R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Platform: x86_64-conda-linux-gnu (64-bit)
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Amazon Linux 2
Matrix products: default
BLAS/LAPACK: /miniconda3/lib/libopenblasp-r0.3.21.so
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] compiler_4.2.2

Step 21/34 : RUN R -e ".libPaths()"
> .libPaths()
[1] "/miniconda3/lib/R/library"
```

```
Step 24/34 : RUN python -m rpy2.situation
 ---> Running in 497d5af8a431
rpy2 version:
3.5.10
Python version:
3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
Looking for R's HOME:
    Environment variable R_HOME: None
    Calling `R RHOME`: /miniconda3/lib/R
    Environment variable R_LIBS_USER: None
R's additions to LD_LIBRARY_PATH:
/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
R version:
    In the PATH: R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/miniconda3/lib/R/include']
  libraries:
  ['R', 'pcre2-8', 'lzma', 'bz2', 'z', 'rt', 'dl', 'm', 'iconv', 'icuuc', 'icui18n']
  library_dirs:
  ['/miniconda3/lib', '/miniconda3/lib/R/lib', '/miniconda3/lib']
  extra_compile_args:
  ['-std=c99']
  extra_link_args:
  ['-Wl,--export-dynamic', '-fopenmp', '-Wl,-O2', '-Wl,--sort-common', '-Wl,--as-needed', '-Wl,-z,relro', '-Wl,-z,now', '-Wl,--disable-new-dtags', '-Wl,--gc-sections', '-Wl,--allow-shlib-undefined', '-Wl,-rpath,/miniconda3/lib', '-Wl,-rpath-link,/miniconda3/lib']
Directory for the R shared library:
lib
CFFI extension type
  Environment variable: RPY2_CFFI_MODE
  Value: CFFI_MODE.ANY
  ABI: PRESENT
  API: PRESENT
```

```
Step 29/34 : RUN which python
/miniconda3/bin/python

Step 30/34 : RUN whereis R
R: /usr/bin/R /usr/lib/R /miniconda3/bin/R

Step 31/34 : RUN which R
/miniconda3/bin/R
```

**Comment by elsiel23** [comment]
My lambda_handler.py is:

```
import rpy2.robjects as robjects

def lambda_handler(event, context):     
    r=robjects.r
    base = importr('base')
    r.source('rank.R')
    r_f = robjects.r['times2']
    result = r_f(4)
    return { 
        'message' : str(result)
    }
```

**Comment by elsiel23** [comment]
I have 2 thoughts on how to approach this:

1) Using all the original python packages. 
Use /var/lang/bin/python and /var/lang/bin/pip. pip install rpy2. Install all R packages with Miniconda (the same as what I'm doing now) Sym link /miniconda3/bin/R to /var/lang/bin/R

2) Use all the miniconda packages.
Use /miniconda3/bin/python and /miniconda3/bin/pip. Use Miniconda to install rpy2. Sym link /miniconda3/bin/python to /var/lang/bin/python

**Comment by lgautier** [comment]
It could also be related to dynamic loading of the R shared C library. Try setting `LD_LIBRARY_PATH` as ishown here:  https://github.com/rpy2/rpy2#non-system-r-installations

This is almost certainly an issue with conda packaging and/or your system's setup rather than an rpy2 issue. I am closing this. Reopen if it is an rpy2 issue.
