### ISSUE TITLE
rpy2 ipython kills ipython kernel when anndata matrix is called.

### ISSUE THREAD

**Issue by IronSpirit** [rpy2/rpy2#1008]
I am trying to call anndata with reticulate package (which is scRNA data). I can read anndata in %%R, I can access uns, and obs, but I can't access to anndata's raw data. (which is ndarray 2D data with float32 data type)

I am using Vs code with jupyter extensions.

I am using python kernel which was installed in mamba forge environment.
and I installed my R with command line 'mamba install r-seurat' in the mamba forge environment that I use for VScode python kernel.

Data is retina.h5ad which is transformed from retina.loompy which was downloaded from scvi tool.  

python version 3.8
rpy2 3.5.10
scanpy 1.9.3

R version 4.3.2
reticulate version 1.26

here's my code

> import rpy2.ipython
> import scanpy as sc
> from scipy import io
> import scipy

> %load_ext rpy2.ipython

> %%R
> library(reticulate)
> 
> sc <- import("scanpy")
> adata <- sc$read_h5ad('./data/retina.h5ad')
> adata$X

**Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further**

This is the error code. And further error message is 

-------------------------------------------------------------------------------------------------------------------------------------------------
info 14:15:20.858: Started Kernel testr (Python 3.8.16) (pid: 60501)
info 14:15:20.877: Process Execution: > ~/mambaforge/envs/testr/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/printJupyterDataDir.py
> ~/mambaforge/envs/testr/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/printJupyterDataDir.py
error 14:15:46.334: Disposing session as kernel process died ExitCode: undefined, Reason: /home/jkl/mambaforge/envs/testr/lib/python3.8/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/home/jkl/mambaforge/envs/testr/lib/python3.8/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'aec2bffb-e5e7-4f47-9deb-0d4dd8db5103' instead of 'b"aec2bffb-e5e7-4f47-9deb-0d4dd8db5103"'.
  warn(

info 14:15:46.334: Dispose Kernel process 60501.
error 14:15:46.334: Raw kernel process exited code: undefined
error 14:15:46.335: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/home/jkl/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:33213)
	at /home/jkl/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:52265
	at Map.forEach (<anonymous>)
	at y._clearKernelState (/home/jkl/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:52250)
	at y.dispose (/home/jkl/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:45732)
	at /home/jkl/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:127079
	at ee (/home/jkl/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:1552543)
	at dh.dispose (/home/jkl/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:127055)
	at hh.dispose (/home/jkl/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:134354)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 14:15:46.335: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 14:15:46.336: Cancel all remaining cells true || Error || undefined
------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by lgautier** [comment]
You have a few moving parts here, and the example is not self-contained. Try simplifying things until you find the likely source of the issue:
- Can you try if this works without VS code and its jupyter extensions? (using jupyter)
- Can you try if things work when not loading `reticulate`?
- Can you try if things work when loading reticulate but not `scanpy`?

Also, please report the output of `python -m rpy2.situation` as asked in the issue template.
