### ISSUE TITLE
Problem installation R package (windows 10) : Exception ignored from cffi callback (UnicodeDecodeError)

### ISSUE THREAD

**Issue by mservantufc** [rpy2/rpy2#1026]
Trying to install package 'rtdists' using rpy 2 (os = windows 10, IDE = spyder, Anaconda distribution, python 3.9). 

Code:

utils.install_packages('rtdists', repos="https://github.com/rtdists/rtdists/") 

Error:

Exception ignored from cffi callback <function _consolewrite_ex at 0x00000181C9861A60>:
Traceback (most recent call last):
  File "C:\Users\mservant\Anaconda3\envs\venv-ConflictTask\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 133, in _consolewrite_ex
    s = conversion._cchar_to_str_with_maxlen(buf, n, _CCHAR_ENCODING)
  File "C:\Users\mservant\Anaconda3\envs\venv-ConflictTask\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 138, in _cchar_to_str_with_maxlen
    s = ffi.string(c, maxlen).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 123: invalid continuation byte
R[write to console]: Warning:
Exception ignored from cffi callback <function _consolewrite_ex at 0x00000181C9861A60>:
Traceback (most recent call last):
  File "C:\Users\mservant\Anaconda3\envs\venv-ConflictTask\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 133, in _consolewrite_ex
    s = conversion._cchar_to_str_with_maxlen(buf, n, _CCHAR_ENCODING)
  File "C:\Users\mservant\Anaconda3\envs\venv-ConflictTask\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 138, in _cchar_to_str_with_maxlen
    s = ffi.string(c, maxlen).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 17: invalid continuation byte
R[write to console]: Warning:
Exception ignored from cffi callback <function _consolewrite_ex at 0x00000181C9861A60>:
Traceback (most recent call last):
  File "C:\Users\mservant\Anaconda3\envs\venv-ConflictTask\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 133, in _consolewrite_ex
    s = conversion._cchar_to_str_with_maxlen(buf, n, _CCHAR_ENCODING)
  File "C:\Users\mservant\Anaconda3\envs\venv-ConflictTask\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 138, in _cchar_to_str_with_maxlen
    s = ffi.string(c, maxlen).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 17: invalid continuation byte
Out[9]: <rpy2.rinterface_lib.sexp.NULLType object at 0x00000181C9A66980> [RTYPES.NILSXP]

**Comment by lgautier** [comment]
Likely related if not identical to issue #1018 .

**Comment by lgautier** [comment]
This is likely because `rpy2` is (wrongly) assuming UTF-8 strings.
There is an unmerged PR (https://github.com/rpy2/rpy2/pull/1020). Can you check if this solves the issue?
