### ISSUE TITLE
I can't install rpy2 3.5.12 on windows 10 python 3.9.

### ISSUE THREAD

**Issue by alekin2** [rpy2/rpy2#1028]
**Describe the issue or bug**

I can't install rpy2 3.5.12 on windows 10 and python 3.9 (anaconda).

**To Reproduce**

Open cmd as administrator
```
C:\WINDOWS\system32>pip install rpy2
```

**Expected behavior**
install rpy2

**Error**
```
Collecting rpy2
  Using cached rpy2-3.5.12.tar.gz (217 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "C:\Users\utente\Anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\utente\Anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\utente\Anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\utente\AppData\Local\Temp\pip-build-env-yz0b4egg\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\utente\AppData\Local\Temp\pip-build-env-yz0b4egg\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\utente\AppData\Local\Temp\pip-build-env-yz0b4egg\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 124, in <module>
        File "<string>", line 110, in get_r_c_extension_status
        File "./rpy2/situation.py", line 295, in get_r_flags
          _get_r_cmd_config(r_home, flags,
        File "./rpy2/situation.py", line 255, in _get_r_cmd_config
          output = subprocess.check_output(
        File "C:\Users\utente\Anaconda3\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\utente\Anaconda3\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\utente\Anaconda3\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\utente\Anaconda3\lib\subprocess.py", line 1420, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```
note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by alekin2** [comment]
rpy2 3.5.13 solve problem!

**Comment by lgautier** [comment]
Thanks. Now we have to figure out why `3.5.13` breaks the install for some Linux setups.

**Comment by alekin2** [comment]
The real problem was the R installation which was 4.2 and was not compatible.
Try to install R 4.3.1 and set R_HOME to C:\Program Files\R\R-4.3.1
reboot pc, then pip install rpy2 from administrator cmd.
I tried on a second pc and that fixed the problem. 
rpy2 3.5.13 was a red herring!

**Comment by weizhii** [comment]
i have r 4.3.1 python3.9  ,and set R_HOME to r install path.
i use pip install rpy2 ,rpy2 version 3.5.12 、3.5.13  error.
i try install rpy2 3.5.7，success.
