### ISSUE TITLE
Error when trying to install rpy2

### ISSUE THREAD

**Issue by zivlang** [rpy2/rpy2#1032]
When using the command 'pip install rpy2', the following error message is printed:

    Collecting rpy2
      Using cached rpy2-3.5.12.tar.gz (217 kB)
      Installing build dependencies ... done
      Getting requirements to build wheel ... error
      error: subprocess-exited-with-error

      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> [28 lines of output]
          Traceback (most recent call last):
            File "c:\users\97254\working_project\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
              main()
            File "c:\users\97254\working_project\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "c:\users\97254\working_project\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel

              return hook(config_settings)
            File "C:\Users\97254\AppData\Local\Temp\pip-build-env-b21o8iu5\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
              return self._get_build_requires(config_settings, requirements=['wheel'])
            File "C:\Users\97254\AppData\Local\Temp\pip-build-env-b21o8iu5\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
              self.run_setup()
            File "C:\Users\97254\AppData\Local\Temp\pip-build-env-b21o8iu5\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
              exec(code, locals())
            File "<string>", line 124, in <module>
            File "<string>", line 110, in get_r_c_extension_status
            File "./rpy2/situation.py", line 295, in get_r_flags
              _get_r_cmd_config(r_home, flags,
            File "./rpy2/situation.py", line 255, in _get_r_cmd_config
              output = subprocess.check_output(
            File "C:\Users\97254\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 420, in check_output
              return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
            File "C:\Users\97254\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run
              with Popen(*popenargs, **kwargs) as process:
            File "C:\Users\97254\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
              self._execute_child(args, executable, preexec_fn, close_fds,
            File "C:\Users\97254\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
              hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
          FileNotFoundError: [WinError 2] The system cannot find the file specified
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mohamedbahru** [comment]
I also got the same error. Dont know how to fix it.

**Comment by alekin2** [comment]
Try to install R 4.3.1 and set R_HOME to C:\Program Files\R\R-4.3.1
reboot pc, then pip install rpy2 from administrator cmd.

**Comment by lgautier** [comment]
With https://github.com/rpy2/rpy2/pull/1128 merged, building binaries in the API mode (the preferred mode) seems to be working. 

I uploaded binaries for Python 3.9 to 3.12 and the dev version of rpy2-3.6.0.  Building for Python 3.13 might work the same way but I have not tried yet.

To install for Python 3.9 to 3.12 the following should just work:
```
pip install -U --pre rpy2-rinterface rpy2-robjects
```
