### ISSUE TITLE
Error when installing rpy2 3.5.13

### ISSUE THREAD

**Issue by pur80a** [rpy2/rpy2#1045]
**Describe the issue or bug**
installation via pip fails 

**To Reproduce**

R version: 4.3.1, 4.3.0, 4.2.3
python version: 3.11.4, 3.7.17

```
python3 -m pip install rpy2==3.5.13 --target /home/apps/rpy2/3.5.13
```

**Error**
```
INFO: installing via PyPi:  rpy2==3.5.13
Collecting rpy2==3.5.13
  Using cached rpy2-3.5.13.tar.gz (218 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      /bin/ld: warning: libRblas.so, needed by /home/apps/R/4.3.0/lib64/R/lib/libR.so, not found (try using -rpath or -rpath-link)
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `zgemm_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `daxpy_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `dgemv_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `dscal_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `dnrm2_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `dgemm_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `dtrsm_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `dcopy_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `dsyrk_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `dasum_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `ddot_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `drotg_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `drot_'
      /home/apps/R/4.3.0/lib64/R/lib/libR.so: undefined reference to `dswap_'
      collect2: error: ld returned 1 exit status
      Traceback (most recent call last):
        File "/tmp/pip-build-env-m1f3b8or/overlay/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 266, in link
          self.spawn(linker + ld_args)
        File "/tmp/pip-build-env-m1f3b8or/overlay/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/tmp/pip-build-env-m1f3b8or/overlay/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/bin/gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/home/apps/python3/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/apps/python3/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/apps/python3/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-m1f3b8or/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-m1f3b8or/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-m1f3b8or/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 124, in <module>
        File "<string>", line 118, in get_r_c_extension_status
        File "<string>", line 81, in get_c_extension_status
        File "/tmp/pip-build-env-m1f3b8or/overlay/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 781, in link_executable
          self.link(
        File "/tmp/pip-build-env-m1f3b8or/overlay/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 268, in link
          raise LinkError(msg)
      distutils.errors.LinkError: command '/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Additional context**
installing rpy2 3.5.12 works for python version 3.7-3.11 

Any help or hints would be appreciated

**Comment by lgautier** [comment]
How was R installed? Do you have LD_LIBRARY_PATH set? Did you try setting it like described here (https://github.com/rpy2/rpy2#issues-loading-shared-c-libraries)?

**Comment by pur80a** [comment]
Thanks for the quick reply!
Installation of R: 
```
TARGET=4.3.1
TMPDIR=`mktemp -d`
pushd $TMPDIR
mkdir /home/apps/R/$TARGET
mkdir /home/apps/R/$TARGET/lib

wget https://cran.r-project.org/src/base/R-${TARGET:0:1}/R-$TARGET.tar.gz
tar xzf R-$TARGET.tar.gz
cd R-$TARGET/
./configure --prefix=/home/apps/R/$TARGET --enable-R-shlib
make
make check
make info
make pdf
make install
make install-info
make install-pdf
popd
rm -rf $TMPDIR
```

`LD_LIBRARY_PATH` is set to `/home/apps/R/4.3.1/lib64`

Setting the variable as mentioned in the link does not work because rpy2 does not install. 
I tried it for the previous version and it returned me `/home/apps/python3/3.11.4/lib:/home/apps/R/4.3.1/lib64`, which is the exact content of `LD_LIBRARY_PATH` 

I forgot to mentioned that I am working with [environment modules](https://modules.sourceforge.net/)

**Comment by lgautier** [comment]
Thanks. I am not familiar with environment modules. I am quite unsure about what would cause rpy2-3.5.12 to install but rpy2-3.5.13 to fail.

I suspect that R picks up a system or an environment modules-installed BLAS library but that library is no longer known to the linker when trying to install rpy2. The following command ran after building/installing R should where is BLAS:

```sh
R CMD config BLAS_LIBS
```

May be something like this is needed:
```sh
module load blas
# or
module load openblas
```

**Comment by lgautier** [comment]
I am continuing comment on issue #1043. That other issue does not have environment modules as an added possible contributing factor.

**Comment by pur80a** [comment]
I've subscribed to issue #1043 and will check again on Monday. 
Thanks!
