### ISSUE TITLE
"Unable to determine R home: [Errno 2] No such file or directory: 'R'' - PyCharm - Mac

### ISSUE THREAD

**Issue by PeterNSteinmetz** [rpy2/rpy2#1058]
I am no longer able to run rpy2 from a python program in PyCharm. This worked just a few weeks ago. 

The exact error is:
```
`Unable to determine R home: [Errno 2] No such file or directory: 'R'
Traceback (most recent call last):
  File "/Users/peter/Research/SpikeSortWork/SpikeSortWork/BmlSorting/GradeOneExperiment.py", line 6, in <module>
    from BmlSorting.BmlStatsGrader import BmlStatsGrader
  File "/Users/peter/Research/SpikeSortWork/SpikeSortWork/BmlSorting/BmlStatsGrader.py", line 10, in <module>
    import rpy2.robjects as ro
  File "/Users/peter/Documents/GitosisRepositories/bmlNeo/venv/lib/python3.10/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/Users/peter/Documents/GitosisRepositories/bmlNeo/venv/lib/python3.10/site-packages/rpy2/rinterface.py", line 19, in <module>
    from rpy2.rinterface_lib import openrlib
  File "/Users/peter/Documents/GitosisRepositories/bmlNeo/venv/lib/python3.10/site-packages/rpy2/rinterface_lib/openrlib.py", line 58, in <module>
    rlib = _dlopen_rlib(R_HOME)
  File "/Users/peter/Documents/GitosisRepositories/bmlNeo/venv/lib/python3.10/site-packages/rpy2/rinterface_lib/openrlib.py", line 45, in _dlopen_rlib
    raise ValueError('r_home is None. '
ValueError: r_home is None. Try python -m rpy2.situation
```

I am now using rpy2 version 3.5.13.

Output from the suggested command is:

```
`rpy2 version:
3.5.13
Python version:
3.10.10 (main, Feb 16 2023, 02:55:02) [Clang 14.0.0 (clang-1400.0.29.202)]
Looking for R's HOME:
    Environment variable R_HOME: None
    Calling 'R RHOME': /Library/Frameworks/R.framework/Resources
    Environment variable R_LIBS_USER: None
R's value for LD_LIBRARY_PATH:
[1] "running startup"

R version:
    In the PATH: R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/Library/Frameworks/R.framework/Resources/include']
  libraries:
  ['pcre2-8', 'lzma', 'bz2', 'z', 'icucore', 'dl', 'm', 'iconv']
  library_dirs:
  ['/usr/local/lib', '/usr/local/lib']
  extra_compile_args:
  ['-std=c99']
  extra_link_args:
  ['-F/Library/Frameworks/R.framework/..', '-framework', 'R']
Directory for the R shared library:
lib
CFFI extension type
  Environment variable: RPY2_CFFI_MODE
  Value: CFFI_MODE.ANY
  ABI: PRESENT
  API: PRESENT
`
```

It is rather unclear why it is now requiring an R_HOME to be set when that wasn't an issue previously. 

```
`R --version` gives:
`R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.
`
```

This is set to a x86_64 architecture to work around the bug mentioned in #900

**Comment by PeterNSteinmetz** [comment]
Further investigation. Line 74 of situation.py in function r_home_from_subprocess is raising a FileNotFoundError as noted in the comment on the next line. 'No such file or directory R'. 

If I take out a terminal window in PyCharm and execute `R RHOME` I obtain '/Library/Frameworks/R.framework/Resources' from this command, which is correct. 

So it appears that process module is not using the proper path to find R. I have it installed using homebrew so /usr/local/bin/R -> /Library/Frameworks/R.framework/Resources/bin/R . 

How should this be working?

**Comment by lgautier** [comment]
Something unexpected seems to be happening. Rpy2 gets the path to `RHOME` from either the first `R` command in the `PATH` or an environment variable `R_HOME` that sets it.

My initial guess is that the process environment for your PyCharm no longer has `R` in the `PATH`. Can you try the following in PyCharm?

```
import os
# The PATH to R should be there:
print(os.environ['PATH'])

# Get the RHOME.
print(os.system('R RHOME'))
```

**Comment by PeterNSteinmetz** [comment]
Very strange. Now this is working. I will close for now and re-open if this re-occurs.
