### ISSUE TITLE
install rpy2 failed "ld: library not found for -lpcre2-8" on Mac

### ISSUE THREAD

**Issue by limin321** [rpy2/rpy2#1061]
**Describe the issue or bug**

I am using a Mac M2. Trying to install rpy2 through jupyter notebook running on Visual Studio Code. And it failed with the following error. My R is v4.3.0, python is v3.10.10.

Here is my code in jupyter notebook:
`!pip install rpy2`

**Error**
Collecting rpy2
  Using cached rpy2-3.5.13.tar.gz (218 kB)
  Installing build dependencies ...   Getting requirements to build wheel ... error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      ld: library not found for -lpcre2-8
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      Traceback (most recent call last):
        File "/private/var/folders/sw/f8mx4xlx5n1_1_6c3cxx4cvc0000gp/T/pip-build-env-wc_jh9i_/overlay/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 266, in link
          self.spawn(linker + ld_args)
        File "/private/var/folders/sw/f8mx4xlx5n1_1_6c3cxx4cvc0000gp/T/pip-build-env-wc_jh9i_/overlay/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/private/var/folders/sw/f8mx4xlx5n1_1_6c3cxx4cvc0000gp/T/pip-build-env-wc_jh9i_/overlay/lib/python3.10/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/lXYZ/miniconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
...
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Additional context**
My mac has a prce2 available as here:
(base)  ~ % ls /opt/homebrew/opt/pcre2
AUTHORS			INSTALL_RECEIPT.json	README			lib
COPYING			LICENCE			bin			share
ChangeLog		NEWS			include
(base) ~ % ls /opt/homebrew/opt/pcre2/lib
libpcre2-16.0.dylib	libpcre2-32.a		libpcre2-8.dylib	pkgconfig
libpcre2-16.a		libpcre2-32.dylib	libpcre2-posix.3.dylib
libpcre2-16.dylib	libpcre2-8.0.dylib	libpcre2-posix.a
libpcre2-32.0.dylib	libpcre2-8.a		libpcre2-posix.dylib

Even I added the above path to environment variable PATH, still it fails with the same error. 

Any suggestion how to solve this will be really helpful.

Best,
LC

**Comment by lgautier** [comment]
`distutils` was used for the install process up until 3.5.13. However, its replacement by `setuptools` was incomplete. There were reports of weird things happen for some setups. Does rpy2 3.5.14 (just released) solve the issue?

**Comment by mingjiang7940** [comment]
> `distutils` was used for the install process up until 3.5.13. However, its replacement by `setuptools` was incomplete. There were reports of weird things happen for some setups. Does rpy2 3.5.14 (just released) solve the issue?

This problem also exists in rpy2 3.5.14, how should I solve it?
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple rpy2
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting rpy2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/30/dc/d9748ec2b61b6a1fcbaff3891961297c83cfa34c9f9984761fb6f6ae65d0/rpy2-3.5.14.tar.gz (219 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      /XSoftware/miniconda3/envs/xteam.py3.8/bin/../lib/gcc/x86_64-conda-linux-gnu/11.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lpcre2-8
      /XSoftware/miniconda3/envs/xteam.py3.8/bin/../lib/gcc/x86_64-conda-linux-gnu/11.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -ltirpc
      collect2: error: ld returned 1 exit status
      Traceback (most recent call last):
        File "/tmp/pip-build-env-8r_bjlfb/overlay/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 266, in link
          self.spawn(linker + ld_args)
        File "/tmp/pip-build-env-8r_bjlfb/overlay/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/tmp/pip-build-env-8r_bjlfb/overlay/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/XSoftware/miniconda3/envs/xteam.py3.8/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/XSoftware/miniconda3/envs/xteam.py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/XSoftware/miniconda3/envs/xteam.py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/XSoftware/miniconda3/envs/xteam.py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-8r_bjlfb/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-8r_bjlfb/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-8r_bjlfb/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 137, in <module>
        File "<string>", line 117, in get_r_c_extension_status
        File "<string>", line 82, in get_c_extension_status
        File "/tmp/pip-build-env-8r_bjlfb/overlay/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 781, in link_executable
          self.link(
        File "/tmp/pip-build-env-8r_bjlfb/overlay/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 268, in link
          raise LinkError(msg)
      distutils.errors.LinkError: command '/XSoftware/miniconda3/envs/xteam.py3.8/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mcornejo** [comment]
I had the same issue and I fixed it in my Macbook (Apple Silicon) by installing libdeflate and exporting the flags:
```bash
brew install libdeflate
export LDFLAGS="-L/opt/homebrew/lib"
export CPPFLAGS="-I/opt/homebrew/include"
export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/lib"
pip install rpy2
```
