### ISSUE TITLE
rpy2.robject cannot be imported with an UnicodeDecodeError message on 

### ISSUE THREAD

**Issue by k1-ito** [rpy2/rpy2#1063]
**Describe the issue or bug**

A clear and concise description of what the issue or bug is. 

Please note that this to report demonstrated or suspected issues or bugs with rpy2. Check the project's documentation or Stackoverflow to check whether the answer can be found there.

```
import os
os.environ['R_HOME'] = 'C:/R/R-4.3.1'
import rpy2
import rpy2.robjects as robjects

Exception ignored from cffi callback <function _consolewrite_ex at 0x000001453E1BF880>:
Traceback (most recent call last):
  File "C:\Users\k1ito\.virtualenv\spyder3.11\Lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 133, in _consolewrite_ex
    s = conversion._cchar_to_str_with_maxlen(buf, n, _CCHAR_ENCODING)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\k1ito\.virtualenv\spyder3.11\Lib\site-packages\rpy2\rinterface_lib\conversion.py", line 138, in _cchar_to_str_with_maxlen
    s = ffi.string(c, maxlen).decode(encoding)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 40: invalid start byte


Windows fatal exception: code 0xc0000028


Main thread:
Current thread 0x00002cdc (most recent call first):
  File "C:\Users\k1ito\.virtualenv\spyder3.11\Lib\site-packages\rpy2\rinterface_lib\embedded_mswin.py", line 76 in _initr_win32
  File "C:\Users\k1ito\.virtualenv\spyder3.11\Lib\site-packages\rpy2\rinterface.py", line 1054 in initr_simple
  File "C:\Users\k1ito\.virtualenv\spyder3.11\Lib\site-packages\rpy2\robjects\robject.py", line 11 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940 in exec_module
  File "<frozen importlib._bootstrap>", line 690 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "C:\Users\k1ito\.virtualenv\spyder3.11\Lib\site-packages\rpy2\robjects\__init__.py", line 21 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940 in exec_module
  File "<frozen importlib._bootstrap>", line 690 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "C:\Users\k1ito\AppData\Local\Temp\ipykernel_18260\1880420087.py", line 1 in <module>
Restarting kernel...
```

If this is an issue about installing the software, provide as much information about your system as you think is related: conda used? virtualenv used? environment variables influencing the behavior of R or Python? version for R, Python, and rpy2? Provide also the exact steps followed.

If this is an issue about the rpy2 code, provide all the above, and a minimal code example to trigger the issue. If data is used, that data will be needed to reproduce the issue.

**Expected behavior**

**Error**
A copy of the error message.

**Additional context**
Providing the output of running `python -m rpy2.situation` is highly recommended.

**Comment by lgautier** [comment]
There is likely an encoding issue with rpy2 assuming utf-8 in more places than it should. Can you try if PR #1020 helps?

**Comment by k1-ito** [comment]
Sorry for the late reply.
Unfortunately, the result remains the same.

What I tried are:
1. download the zip file of `the consistent_r2py_str_encoding-issue1018` branch
1. `pip uninstall rpy2`
1. `pip cache purge`
1. unzip the zip file
1. `pip install .\rpy2-consistent_r2py_str_encoding-issue1018`

**Comment by k1-ito** [comment]
After installing rpy2 3.6.0 and Rtools 4.5 (6536-6492), the problem has been solved in my environment.

Python 3.13.4
Windows 11 Pro 24H2 Build: 26100.4061

**Comment by k1-ito** [comment]
and adding C:\rtools45\usr\bin and C:\rtools45\mingw64\bin to PATH.

**Comment by lgautier** [comment]
Any specific reason to suspect `argon-cffi` ?

Otherwise rpy2-3.6.1 should be released soon. You can fetch a pre-release Windows built in Section "Artifacts" here: https://github.com/rpy2/rpy2/actions/runs/15499106400

**Comment by lgautier** [comment]
Thanks. From the error message the latest error seems to be a duplicate of #1183.

**Comment by k1-ito** [comment]
I have installed rpy 3.6.1. It seems the `UnicodeDecodeError` issue has come back. 
Below is the error messages when I run `from rpy2.robjects.packages import importr`.

```
Error importing in API mode: ImportError('On Windows, cffi mode "ANY" is only "ABI".')
Trying to import in ABI mode.
C:\Users\k1ito\.virtualenv\spyder3.13\Lib\site-packages\rpy2\rinterface\__init__.py:1211: UserWarning: Environment variable "PATH" redefined by R and overriding existing variable. Current: "C:\Users\k1ito\.virtualenv\spyder3.13\Lib\site-packages\PyQt5\Qt5\bin;C:\Users\k1ito\.virtualenv\spyder3.13\Lib\site-packages\PyQt5\Qt5\bin;C:\Users\k1ito\.virtualenv\spyder3.13/Scripts;C:\Program Files\PowerShell\7;C:\Program Files (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\FAHClient;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\PROGRA~1\JPKI;C:\Program Files (x86)\PDFtk\bin\;C:\Program Files\NVIDIA Corporation\NVIDIA app\NvDLISR;C:\Program Files\PowerShell\7\;C:\Users\k1ito\AppData\Local\Microsoft\WindowsApps;C:\Users\k1ito\.dotnet\tools;C:\otherApplication\aviutl110\exe_files;C:\otherApplication\mkvtoolnix;C:\otherApplication\ffmpeg\ffmpeg-7.0.2-essentials_build\bin;C:\Users\k1ito\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\RStudio\resources\app\bin\quarto\bin;C:\texlive\2025\bin\windows;C:\otherApplication\Sumatra;C:\rtools45\usr\bin;C:/R/R-4.5.0\bin\x64", R: "C:\rtools45/x86_64-w64-mingw32.static.posix/bin;C:\rtools45/usr/bin;C:\Users\k1ito\.virtualenv\spyder3.13\Lib\site-packages\PyQt5\Qt5\bin;C:\Users\k1ito\.virtualenv\spyder3.13\Lib\site-packages\PyQt5\Qt5\bin;C:\Users\k1ito\.virtualenv\spyder3.13/Scripts;C:\Program Files\PowerShell\7;C:\Program Files (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\FAHClient;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\PROGRA~1\JPKI;C:\Program Files (x86)\PDFtk\bin\;C:\Program Files\NVIDIA Corporation\NVIDIA app\NvDLISR;C:\Program Files\PowerShell\7\;C:\Users\k1ito\AppData\Local\Microsoft\WindowsApps;C:\Users\k1ito\.dotnet\tools;C:\otherApplication\aviutl110\exe_files;C:\otherApplication\mkvtoolnix;C:\otherApplication\ffmpeg\ffmpeg-7.0.2-essentials_build\bin;C:\Users\k1ito\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\RStudio\resources\app\bin\quarto\bin;C:\texlive\2025\bin\windows;C:\otherApplication\Sumatra;C:\rtools45\usr\bin;C:/R/R-4.5.0\bin\x64"
  warnings.warn(
R callback write-console: <class 'UnicodeDecodeError'> 'utf-8' codec can't decode byte 0xb4 in position 40: invalid start byte <traceback object at 0x00000190FF389C80>


The kernel died, restarting...
```

Just additional information:
```
> python -m rpy2.situation
CFFI extension type
  ABI: PRESENT
  API: PRESENT
  Environment variable: RPY2_CFFI_MODE=ANY
Error importing in API mode: ImportError('On Windows, cffi mode "ANY" is only "ABI".')
Trying to import in ABI mode.
  Loaded: CFFI_MODE.ABI
rpy2 version:
rpy2.rinterface: 3.6.1
Python version:
3.13.4 (tags/v3.13.4:8a526ec, Jun  3 2025, 17:46:04) [MSC v.1943 64 bit (AMD64)]
Looking for R's HOME:
  Environment variable R_HOME: None
  InstallPath in the registry: C:\R\R-4.5.0
  Environment variable R_USER: None
  Environment variable R_LIBS_USER: None
R version:
  In the PATH: R version 4.5.0 (2025-04-11 ucrt) -- "How About a Twenty-Six"
  Loading R library from rpy2: OK
Additional directories to load R packages from:
  None
C extension compilation:
  include:
    ['C:/R/R-4.5.0/include', 'C:/R/R-4.5.0/include/x64']
  libraries:
    ['R', 'm']
  library_dirs:
    ['C:/R/R-4.5.0/bin/x64']
  extra_compile_args:
    ['-std=c99']
  extra_link_args:
    []
  Directory for the R shared library:
    lib
```

**Comment by k1-ito** [comment]
Thank you very much for your suggestions.
The results are:
```python
import sys
print(f'sys.getdefaultencoding: {sys.getdefaultencoding()'}
sys.getdefaultencoding: utf-8
``` 

```python
import locale
print(f'locale.getpreferredencoding: {locale.getpreferredencoding()}')
locale.getpreferredencoding: cp932
``` 

I ran `python -m trace --trace myscript.py`, but I am afraid I couldn't figure out what I should report as the code apparently terminated without crashing and I couldn't tell which lines are suspicious.

I am not sure this is the right answer to your suggestion, but instead I tried running `python -m trace --trace myscript.py | Out-File -FilePath "trace_output.txt".` I paste some of the results below. Please point out if I should do something else.

The last lines of `trace_output.txt` are
```
 --- modulename: shlex, funcname: split
shlex.py(307):      if s is None:
shlex.py(309):      lex = shlex(s, posix=posix)
 --- modulename: shlex, funcname: __init__
shlex.py(23):          if isinstance(instream, str):
shlex.py(24):              instream = StringIO(instream)
shlex.py(25):          if instream is not None:
shlex.py(26):              self.instream = instream
shlex.py(27):              self.infile = infile
shlex.py(31):          self.posix = posix
shlex.py(32):          if posix:
shlex.py(33):              self.eof = None
shlex.py(36):          self.commenters = '#'
shlex.py(37):          self.wordchars = ('abcdfeghijklmnopqrstuvwxyz'
shlex.py(39):          if self.posix:
shlex.py(40):  
```
The powershell output is:
```powershell
python -m trace --trace myscript.py | Out-File -FilePath "trace_output.txt"

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\k1ito\AppData\Local\Programs\Python\Python313\Lib\trace.py", line 754, in <module>
    main()
    ~~~~^^
  File "C:\Users\k1ito\AppData\Local\Programs\Python\Python313\Lib\trace.py", line 742, in main
    t.runctx(code, globs, globs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\k1ito\AppData\Local\Programs\Python\Python313\Lib\trace.py", line 456, in runctx
    exec(cmd, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "myscript.py", line 1, in <module>
    from rpy2.robjects.packages import importr
  File "C:\Users\k1ito\.virtualenv\spyder3.13\Lib\site-packages\rpy2\robjects\__init__.py", line 17, in <module>
    import rpy2.rinterface as rinterface
  File "C:\Users\k1ito\.virtualenv\spyder3.13\Lib\site-packages\rpy2\rinterface\__init__.py", line 22, in <module>
    from rpy2.rinterface_lib import openrlib
  File "C:\Users\k1ito\.virtualenv\spyder3.13\Lib\site-packages\rpy2\rinterface_lib\openrlib.py", line 19, in <module>
    for libpath in rpy2.situation.get_r_flags(R_HOME, '--ldflags')[0].L:
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\k1ito\.virtualenv\spyder3.13\Lib\site-packages\rpy2\situation\__init__.py", line 284, in get_r_flags
    res = shlex.split(
        ' '.join(
            _get_r_cmd_config(r_home, flags,
                              allow_empty=False)))
  File "C:\Users\k1ito\AppData\Local\Programs\Python\Python313\Lib\shlex.py", line 309, in split
    lex = shlex(s, posix=posix)
  File "C:\Users\k1ito\AppData\Local\Programs\Python\Python313\Lib\shlex.py", line 40, in __init__
    self.wordchars += ('ßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ'
    ^^^^
  File "C:\Users\k1ito\AppData\Local\Programs\Python\Python313\Lib\trace.py", line 588, in localtrace_trace
    print(": ", line, end='')
    ~~~~~^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'cp932' codec can't encode character '\xdf' in position 32: illegal multibyte sequence
```

**Comment by lgautier** [comment]
Thanks. We want content in `trace_output.txt` that is a bit earlier: the last calls still under `rpy2`.

Otherwise I am a little puzzled by the Powershell output. It reports an error here:
https://github.com/rpy2/rpy2/blob/2bbff5e9bf6dc63a88b60bf4ab56bca22efb8ec0/rpy2-rinterface/src/rpy2/situation/__init__.py#L284
However, I think that this code should only be evaluated when installing `rpy2-rinterface`, or when calling `rpy2.situation` as script to report about the installation on the system.

**Comment by k1-ito** [comment]
Sorry for the multiple posts. 
I also have a Windows 11 *Home* notebook. It turned out using Rtools Bash does not work on this notebook.
So at the present, the common method across the three machines to use `importr` is

- use rpy2 3.6.0 and execute `from rpy2.robjects.packages import importr` twice *on Powershell*.

I apologize I will not be able to respond so often as I could for some reasons.
But I am willing to collaborate as much as possible.

**Comment by lgautier** [comment]
(...)
> It is puzzling that, even though I have deleted the manually-added R_HOME and paths to R and rtools binaries from the user environment variables, the machine can still import importr on Powershell. 

If `R_HOME` is not specified, rpy2 gets it  from the registry:
https://github.com/rpy2/rpy2/blob/a92b4ed506aba38b010f6d20702deb32566bc175/rpy2-rinterface/src/rpy2/situation/__init__.py#L85

> Another fact I have found is that both machine can import `importr` on Rtools Bash.
> And when launched from Rtools Bash, both Spyder and Jupyterlab can also import `importr`.
> I have no clue about it at all either.

Rtools is likely ensuring that `sh`/`bash` (and `make`?) are in the PATH. The requirement is reported in #1188.

**Comment by lgautier** [comment]
(...)
> I apologize I will not be able to respond so often as I could for some reasons.
> But I am willing to collaborate as much as possible.

No worries. This is an Open Source project. We all contribute when and if we have the time to.

**Comment by lgautier** [comment]
PR #1230 (now merged) should fix most encoding-related issues. Using an UTF-8 locale is recommended.
