### ISSUE TITLE
localconverter solution doesn't work with python classes for multi-threaded logic

### ISSUE THREAD

**Issue by hguturu** [rpy2/rpy2#1081]
**Describe the issue or bug**

I believe this is a variant of https://github.com/rpy2/rpy2/issues/965 where I am unable to use an class that implements RPy2 in a multi-threading context. We discovered this first with Jupyter Notebooks which fortunately was resolved with updating "ipykernel>6", but there is still an issue with `joblib`.

**To Reproduce**
```py
class RPy2TestClass:
    def __init__(self):
        from rpy2 import rinterface, robjects
        from rpy2.robjects import pandas2ri
        from rpy2.robjects.conversion import localconverter
        from rpy2.robjects.packages import importr

        self.rinterface = rinterface
        self.robjects = robjects
        self.pandas2ri = pandas2ri
        self.localconverter = localconverter
        self.importr = importr

        self.base = self.importr("base")
        self.t = self.robjects.globalenv.find("t")
        self.rownames = self.robjects.globalenv.find("rownames")
        self.colnames = self.robjects.globalenv.find("colnames")

    def always_true(self):
        return True

    def get_pi(self):
        return self.base.pi[0]


def function_to_parallelize1():
    return RPy2TestClass().always_true()


def function_to_parallelize2():
    return RPy2TestClass().get_pi()
```

Given the above class. 

The following works:
```py
import joblib
jobs = [
    joblib.delayed(function_to_parallelize1)(),
    joblib.delayed(function_to_parallelize1)(),
]
joblib.Parallel(n_jobs=2, prefer="processes", verbose=11)(jobs)
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 tasks      | elapsed:    0.6s
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.6s finished
Out[4]: [True, True]

# also works with function_to_parallelize2
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 tasks      | elapsed:    0.5s
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.5s finished
Out[6]: [3.141592653589793, 3.141592653589793]
```

The following throws the expected exception:
```py
import joblib
jobs = [
    joblib.delayed(function_to_parallelize1)(),
    joblib.delayed(function_to_parallelize1)(),
]
joblib.Parallel(n_jobs=2, prefer="threads", verbose=11)(jobs)
[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
/Users/hguturu/miniforge3/lib/python3.10/site-packages/rpy2/rinterface.py:1228: UserWarning: R is not initialized by the main thread.
                Its taking over SIGINT cannot be reversed here, and as a
                consequence the embedded R cannot be interrupted with Ctrl-C.
                Consider (re)setting the signal handler of your choice from
                the main thread.
  warnings.warn(
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/hguturu/miniforge3/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call
    return func()
  File "/Users/hguturu/miniforge3/lib/python3.10/site-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/Users/hguturu/miniforge3/lib/python3.10/site-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "<ipython-input-1-84c79ebb6832>", line 27, in function_to_parallelize1
    return RPy2TestClass().always_true()
  File "<ipython-input-1-84c79ebb6832>", line 14, in __init__
    self.base = self.importr("base")
  File "/Users/hguturu/miniforge3/lib/python3.10/site-packages/rpy2/robjects/packages.py", line 496, in importr
    pack = InstalledSTPackage(env, name,
  File "/Users/hguturu/miniforge3/lib/python3.10/site-packages/rpy2/robjects/packages.py", line 203, in __init__
    self.__fill_rpy2r__(on_conflict=on_conflict)
  File "/Users/hguturu/miniforge3/lib/python3.10/site-packages/rpy2/robjects/packages.py", line 329, in __fill_rpy2r__
    (super(SignatureTranslatedPackage, self)
  File "/Users/hguturu/miniforge3/lib/python3.10/site-packages/rpy2/robjects/packages.py", line 264, in __fill_rpy2r__
    rpyobj = cv.rpy2py(riobj)
  File "/Users/hguturu/miniforge3/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/hguturu/miniforge3/lib/python3.10/site-packages/rpy2/robjects/conversion.py", line 383, in _raise_missingconverter
    raise NotImplementedError(_missingconverter_msg)
NotImplementedError: 
    Conversion rules for `rpy2.robjects` appear to be missing. Those
    rules are in a Python contextvars.ContextVar. This could be caused
    by multithreading code not passing context to the thread.
    
"""

The above exception was the direct cause of the following exception:

NotImplementedError                       Traceback (most recent call last)
Cell In[2], line 6
      1 import joblib
      2 jobs = [
      3     joblib.delayed(function_to_parallelize1)(),
      4     joblib.delayed(function_to_parallelize1)(),
      5 ]
----> 6 joblib.Parallel(n_jobs=2, prefer="threads", verbose=11)(jobs)

File ~/miniforge3/lib/python3.10/site-packages/joblib/parallel.py:1952, in Parallel.__call__(self, iterable)
   1946 # The first item from the output is blank, but it makes the interpreter
   1947 # progress until it enters the Try/Except block of the generator and
   1948 # reach the first `yield` statement. This starts the aynchronous
   1949 # dispatch of the tasks to the workers.
   1950 next(output)
-> 1952 return output if self.return_generator else list(output)

File ~/miniforge3/lib/python3.10/site-packages/joblib/parallel.py:1595, in Parallel._get_outputs(self, iterator, pre_dispatch)
   1592     yield
   1594     with self._backend.retrieval_context():
-> 1595         yield from self._retrieve()
   1597 except GeneratorExit:
   1598     # The generator has been garbage collected before being fully
   1599     # consumed. This aborts the remaining tasks if possible and warn
   1600     # the user if necessary.
   1601     self._exception = True

File ~/miniforge3/lib/python3.10/site-packages/joblib/parallel.py:1699, in Parallel._retrieve(self)
   1692 while self._wait_retrieval():
   1693 
   1694     # If the callback thread of a worker has signaled that its task
   1695     # triggered an exception, or if the retrieval loop has raised an
   1696     # exception (e.g. `GeneratorExit`), exit the loop and surface the
   1697     # worker traceback.
   1698     if self._aborting:
-> 1699         self._raise_error_fast()
   1700         break
   1702     # If the next job is not ready for retrieval yet, we just wait for
   1703     # async callbacks to progress.

File ~/miniforge3/lib/python3.10/site-packages/joblib/parallel.py:1734, in Parallel._raise_error_fast(self)
   1730 # If this error job exists, immediatly raise the error by
   1731 # calling get_result. This job might not exists if abort has been
   1732 # called directly or if the generator is gc'ed.
   1733 if error_job is not None:
-> 1734     error_job.get_result(self.timeout)

File ~/miniforge3/lib/python3.10/site-packages/joblib/parallel.py:736, in BatchCompletionCallBack.get_result(self, timeout)
    730 backend = self.parallel._backend
    732 if backend.supports_retrieve_callback:
    733     # We assume that the result has already been retrieved by the
    734     # callback thread, and is stored internally. It's just waiting to
    735     # be returned.
--> 736     return self._return_or_raise()
    738 # For other backends, the main thread needs to run the retrieval step.
    739 try:

File ~/miniforge3/lib/python3.10/site-packages/joblib/parallel.py:754, in BatchCompletionCallBack._return_or_raise(self)
    752 try:
    753     if self.status == TASK_ERROR:
--> 754         raise self._result
    755     return self._result
    756 finally:

NotImplementedError: 
    Conversion rules for `rpy2.robjects` appear to be missing. Those
    rules are in a Python contextvars.ContextVar. This could be caused
    by multithreading code not passing context to the thread.

# same exception for function_to_parallelize2
```

**Expected behavior**
For the multi-threading code to behave similar to the multi-processing code. I tried the suggested fix of wrapping the imports in `localconverter` as suggested in the previous issue. https://github.com/rpy2/rpy2/issues/965#issuecomment-1366801876

```py
class RPy2TestClass:
    def __init__(self):
        from rpy2 import rinterface, robjects
        from rpy2.robjects import pandas2ri
        from rpy2.robjects.conversion import localconverter
        from rpy2.robjects.packages import importr

        self.rinterface = rinterface
        self.robjects = robjects
        self.pandas2ri = pandas2ri
        self.localconverter = localconverter
        self.importr = importr
        with self.localconverter(
            self.robjects.default_converter + self.pandas2ri.converter
        ):
            self.base = self.importr("base")
            self.t = self.robjects.globalenv.find("t")
            self.rownames = self.robjects.globalenv.find("rownames")
            self.colnames = self.robjects.globalenv.find("colnames")

    def always_true(self):
        return True

    def get_pi(self):
        return self.base.pi[0]

def function_to_parallelize1():
    return RPy2TestClass().always_true()


def function_to_parallelize2():
    return RPy2TestClass().get_pi()
``` 

**Error**
At this point, the `joblib.Parallel(n_jobs=2, prefer="processes", verbose=11)(jobs)` continues working.

But, switching to `joblib.Parallel(n_jobs=2, prefer="threads", verbose=11)(jobs)` causes the following two errors:
```py
import joblib
jobs = [
    joblib.delayed(function_to_parallelize1)(),
    joblib.delayed(function_to_parallelize1)(),
]
joblib.Parallel(n_jobs=2, prefer="threads", verbose=11)(jobs)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
/Users/hguturu/miniforge3/lib/python3.10/site-packages/rpy2/rinterface.py:1228: UserWarning: R is not initialized by the main thread.
                Its taking over SIGINT cannot be reversed here, and as a
                consequence the embedded R cannot be interrupted with Ctrl-C.
                Consider (re)setting the signal handler of your choice from
                the main thread.
  warnings.warn(
R[write to console]: Warning: stack imbalance in 'lazyLoadDBfetch', 1 then 9

R[write to console]: Error in parent.frame() : invalid 'n' value

[1]    50185 segmentation fault  ipython3
/Users/hguturu/miniforge3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

```py
import joblib
jobs = [
    joblib.delayed(function_to_parallelize2)(),
    joblib.delayed(function_to_parallelize2)(),
]
joblib.Parallel(n_jobs=2, prefer="threads", verbose=11)(jobs)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
/Users/hguturu/miniforge3/lib/python3.10/site-packages/rpy2/rinterface.py:1228: UserWarning: R is not initialized by the main thread.
                Its taking over SIGINT cannot be reversed here, and as a
                consequence the embedded R cannot be interrupted with Ctrl-C.
                Consider (re)setting the signal handler of your choice from
                the main thread.
  warnings.warn(
R[write to console]: Error: promise already under evaluation: recursive default argument reference or earlier problems?

[1]    50813 segmentation fault  ipython3
/Users/hguturu/miniforge3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
**Additional context**
Basically wrapping the imports in the `localconverter` seems to make the situation worse since the entire code segfaults. Its odd that it is segfault even when the values are never used again (e.g. in the `always_true` function).

Providing the output of running `python -m rpy2.situation` is highly recommended.
```
rpy2 version:
3.5.14
Python version:
3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:39:40) [Clang 15.0.7 ]
Looking for R's HOME:
    Environment variable R_HOME: None
    Calling `R RHOME`: /Library/Frameworks/R.framework/Resources
    Environment variable R_LIBS_USER: None
R's value for LD_LIBRARY_PATH:

R version:
    In the PATH: R version 4.3.2 (2023-10-31) -- "Eye Holes"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/Library/Frameworks/R.framework/Resources/include']
  libraries:
  ['pcre2-8', 'lzma', 'bz2', 'z', 'icucore', 'dl', 'm', 'iconv']
  library_dirs:
  ['/opt/R/x86_64/lib', '/opt/R/x86_64/lib']
  extra_compile_args:
  ['-std=c99']
  extra_link_args:
  ['-F/Library/Frameworks/R.framework/..', '-framework', 'R']
Directory for the R shared library:
lib
CFFI extension type
  Environment variable: RPY2_CFFI_MODE
  Value: CFFI_MODE.ANY
  ABI: PRESENT
  API: PRESENT
```

**Comment by lgautier** [comment]
The apparent loss of conversion rules originates from what I understand to be `ContextVar` breaking vanilla multi-threading. `ContextVar` works well will `asyncio` out-of-the-box.

Three options from here.

A) Explicitly wrap calls to R into the conversion rules you want to use. When done at the top level it will look like:

```python
def ensure_conversion(func: typing.Callable):
    def wrapper_func(*args, **kwargs):
        with rpy2.robjects.default_converter.context():
            return func(*args, **kwargs)
   return wrapper_func

@ensure_conversion
def function_to_parallelize1():
    return RPy2TestClass().always_true()
```

I do not know to which extent this is thread-safe though. If there is a thread switch during the execution of the wrapped function (here `function_to_parallelize`) and another thread sets conversion rules differently I am not sure about what happens. It does not mean it unsafe. I really don't know and would need to check few things in order to be sure. This is what `ContextVar` is meant to address.

B) Have a way to customize thread initialization (the `__init__()` method for the thread) and add `context_var.copy_context()` to it. 

C) Get this fixed upstream and have joblib's thread-based parallelism handle contexts. I'll look into filing a bug report on the joblib's issue tracker.

Finally, note that R is not thread-friendly at all. You'll want to have all R calls (or Python function with R calls, the highest the granularity the more multi-threading you'll get) with a lock (see https://rpy2.github.io/doc/v3.5.x/html/rinterface.html#multithreading).

**Comment by lgautier** [comment]
Issue caused by parallelization used by the calling code using threads and ignoring contexts / contextvars.
