### ISSUE TITLE
Windows build LINK failures: cannot open input file 'm.lib'

### ISSUE THREAD

**Issue by mfansler** [rpy2/rpy2#1084]
**Describe the issue or bug**

All Conda Forge builds of `rpy2` v3.5.15 are failing on Windows (see https://github.com/conda-forge/rpy2-feedstock/pull/123). The root cause appears to be use of MSVC 14.3 in combination with `-libm`. Searching the error indicates the `m` (math) library is implicit to MSVC 14+ and should not be explicitly linked.

For reference, see [this StackOverflow thread](https://stackoverflow.com/q/19333898/570918). Also, one can see [how `cvxopt` dealt with this](https://github.com/cvxopt/cvxopt/pull/115), namely, they added an environment variable (`MSVC`) to allow users to indicate MSVC 14+ was in use and conditionally omit the `m` library.

**To Reproduce**

See [Conda Forge PR](https://github.com/conda-forge/rpy2-feedstock/pull/123) and CI runs. All Conda Forge recipes can be built locally (will need a Windows machine or VM).

**Expected behavior**
Should build.

**Error**

```python
Using pip 23.3.2 from %BUILD_PREFIX%\lib\site-packages\pip (python 3.10)
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-tracker-6d0co3cg
Initialized build tracking at C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-tracker-6d0co3cg
Created build tracker: C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-tracker-6d0co3cg
Entered build tracker: C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-tracker-6d0co3cg
Created temporary directory: C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-bjluippt
Created temporary directory: C:\Users\VssAdministrator\AppData\Local\Temp\pip-ephem-wheel-cache-4gzsaiwj
Processing d:\bld\rpy2_1703737769356\work
  Added file:///D:/bld/rpy2_1703737769356/work to build tracker 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pip-build-tracker-6d0co3cg'
  Created temporary directory: C:\Users\VssAdministrator\AppData\Local\Temp\pip-modern-metadata-eslgd6fi
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  test_pw_r.c
  LINK : fatal error LNK1181: cannot open input file 'm.lib'
  Traceback (most recent call last):
    File "D:\bld\rpy2_1703737769356\_h_env\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 515, in link
      self.spawn([self.linker] + ld_args)
    File "D:\bld\rpy2_1703737769356\_h_env\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 524, in spawn
      return super().spawn(cmd, env=env)
    File "D:\bld\rpy2_1703737769356\_h_env\lib\site-packages\setuptools\_distutils\ccompiler.py", line 1041, in spawn
      spawn(cmd, dry_run=self.dry_run, **kwargs)
    File "D:\bld\rpy2_1703737769356\_h_env\lib\site-packages\setuptools\_distutils\spawn.py", line 70, in spawn
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
```

**Additional context**
This problem appears similar to #1044, with the exception that `m.lib` is the failure here, whereas there it is `R.lib`.

Conda Forge builds use R 4.1.3 and Python 3.8-3.11.

**Comment by lgautier** [comment]
Thanks for the report.

`rpy2`'s support for Windows is limited. Although I lack the bandwidth to do much about it I started a PR. Trying to compile with MSVC did end with the same issue that you report. IIRC building R on Windows should be done with `mingw`, so I tried to use it. I progressed a little there, but the effort stopped at C statements nor compatible with Windows.

The last CI run for that PR is here: https://github.com/rpy2/rpy2/actions/runs/7358358272?pr=1054

Note that this is when trying to build rpy2 with the API model. It should be fine to build rpy2 in ABI mode only.

PS: R-4.1.3 is a tad old.

**Comment by lgautier** [comment]
In the main branch, the CI pipeline  is building binary wheels for Windows that can install and pass tests. This will be included in release 3.6.0.
