### ISSUE TITLE
Error when installing rpy2 on windows

### ISSUE THREAD

**Issue by tmauceri** [rpy2/rpy2#1124]
**Describe the issue or bug**

installation via pip fails

**To Reproduce**

R version: 4.4.2
Python version: 3.13

`pip install rpy2`

**Error**
`
$ pip install rpy2
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000211B2F63B60>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/rpy2/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000211B2FDC2D0>: Failed to establish a new connection: [WinError 10051] Tentativo di operazione del socket verso una rete non raggiungibile')': /simple/rpy2/
Collecting rpy2
  Using cached rpy2-3.5.16.tar.gz (220 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [64 lines of output]
      test_pw_r.c
      LINK : fatal error LNK1181: non Š possibile aprire il file di input 'R.lib'
      Traceback (most recent call last):
        File "C:\Users\mauceri\AppData\Local\Temp\pip-build-env-6oz3moeh\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 70, in spawn
          subprocess.check_call(cmd, env=_inject_macos_ver(env))
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mauceri\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\link.exe', '/nologo', '/INCREMENTAL:NO', '/LTCG', '/MANIFEST:EMBED,ID=1', '/LIBPATH:C:/Users/mauceri/AppData/Local/Programs/R/R-4.4.2/bin/x64', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\lib\\um\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.22621.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\\\lib\\10.0.22621.0\\\\um\\x64', 'R.lib', 'm.lib', 'C:\\Users\\mauceri\\AppData\\Local\\Temp\\tmp_pw_r_4tlt5i2x\\test_pw_r.obj', '/OUT:C:\\Users\\mauceri\\AppData\\Local\\Temp\\tmp_pw_r_4tlt5i2x\\test_pw_r.exe']' returned non-zero exit status 1181.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\Users\mauceri\AppData\Local\Temp\pip-build-env-6oz3moeh\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 544, in link
          self.spawn([self.linker] + ld_args)
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mauceri\AppData\Local\Temp\pip-build-env-6oz3moeh\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 553, in spawn
          return super().spawn(cmd, env=env)
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^
        File "C:\Users\mauceri\AppData\Local\Temp\pip-build-env-6oz3moeh\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 1045, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
          ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mauceri\AppData\Local\Temp\pip-build-env-6oz3moeh\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 76, in spawn
          raise DistutilsExecError(
              f"command {_debug(cmd)!r} failed with exit code {err.returncode}"
          ) from err
      distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\mauceri\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\mauceri\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mauceri\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\mauceri\AppData\Local\Temp\pip-build-env-6oz3moeh\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mauceri\AppData\Local\Temp\pip-build-env-6oz3moeh\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\mauceri\AppData\Local\Temp\pip-build-env-6oz3moeh\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 141, in <module>
        File "<string>", line 121, in get_r_c_extension_status
        File "<string>", line 82, in get_c_extension_status
        File "C:\Users\mauceri\AppData\Local\Temp\pip-build-env-6oz3moeh\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 787, in link_executable
          self.link(
          ~~~~~~~~~^
              CCompiler.EXECUTABLE,
              ^^^^^^^^^^^^^^^^^^^^^
          ...<11 lines>...
              target_lang,
              ^^^^^^^^^^^^
          )
          ^
        File "C:\Users\mauceri\AppData\Local\Temp\pip-build-env-6oz3moeh\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 546, in link
          raise LinkError(msg)
      distutils.errors.LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

`

**Comment by lgautier** [comment]
The CI pipeline trying to build on Windows is facing the exact same issue. Its seems that the linker from MSVS is picked up somehow. The linker from MingW should be used instead, but I can't seem to get setuptools to comply. I have a question about this here: https://github.com/pypa/setuptools/discussions/4763 . If it gets voted up may be it will receive attention faster.

**Comment by beng1290** [comment]
installing 3.5.12 worked for me on windows, also had to set the R_HOME in os.environ or it crashed on import. 

Thank you for this!

**Comment by lgautier** [comment]
With https://github.com/rpy2/rpy2/pull/1128 merged, building binaries in the API mode (the preferred mode) seems to be working. 

I uploaded binaries for Python 3.9 to 3.12 and the dev version of rpy2-3.6.0.  Building for Python 3.13 might work the same way but I have not tried yet.

To install for Python 3.9 to 3.12 the following should just work:
```
pip install -U --pre rpy2-rinterface rpy2-robjects
```

**Comment by lgautier** [comment]
Binaries build on Python 3.13: https://github.com/rpy2/rpy2/pull/1134
`3.6.0.dev1` binary build were uploaded to pypi.

**Comment by lgautier** [comment]
A dev version with windows binary wheels should now install with: 
```sh
pip install -U --pre rpy2
```
