### ISSUE TITLE
Unable to install rpy2 within new Python environment in Linux

### ISSUE THREAD

**Issue by kburchfiel** [rpy2/rpy2#1126]
I tried installing rpy2 this afternoon within a new Python environment. However, I was unable to do so with both pip and conda.

The following output shows the steps I took and the error messages I received:

(base) kjb3@kjb3-lm:~$ conda activate pyr

### Attempting to install rpy2 using pip:
(pyr) kjb3@kjb3-lm:~$ pip install rpy2
Collecting rpy2
  Using cached rpy2-3.5.16.tar.gz (220 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      /home/kjb3/miniforge3/envs/pyr/shared/python_compiler_compat/ld: cannot find -llzma: No such file or directory
      /home/kjb3/miniforge3/envs/pyr/shared/python_compiler_compat/ld: cannot find -lbz2: No such file or directory
      /home/kjb3/miniforge3/envs/pyr/shared/python_compiler_compat/ld: cannot find -ltirpc: No such file or directory
      collect2: error: ld returned 1 exit status
      Traceback (most recent call last):
        File "/tmp/pip-build-env-4kc5sz45/overlay/lib/python3.13/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          subprocess.check_call(cmd, env=_inject_macos_ver(env))
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/kjb3/miniforge3/envs/pyr/lib/python3.13/subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/gcc', '-pthread', '-B', '/home/kjb3/miniforge3/envs/pyr/shared/python_compiler_compat', '/tmp/tmp_pw_r_ofpcsh03/tmp/tmp_pw_r_ofpcsh03/test_pw_r.o', '-L/usr/lib/R/lib', '-lR', '-lpcre2-8', '-llzma', '-lbz2', '-lz', '-ltirpc', '-lrt', '-ldl', '-lm', '-licuuc', '-licui18n', '-o', '/tmp/tmp_pw_r_ofpcsh03/test_pw_r']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-4kc5sz45/overlay/lib/python3.13/site-packages/setuptools/_distutils/unixccompiler.py", line 287, in link
          self.spawn(linker + ld_args)
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4kc5sz45/overlay/lib/python3.13/site-packages/setuptools/_distutils/ccompiler.py", line 1045, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
          ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4kc5sz45/overlay/lib/python3.13/site-packages/setuptools/_distutils/spawn.py", line 76, in spawn
          raise DistutilsExecError(
              f"command {_debug(cmd)!r} failed with exit code {err.returncode}"
          ) from err
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/kjb3/miniforge3/envs/pyr/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/kjb3/miniforge3/envs/pyr/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/kjb3/miniforge3/envs/pyr/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-4kc5sz45/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-4kc5sz45/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-4kc5sz45/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 141, in <module>
        File "<string>", line 121, in get_r_c_extension_status
        File "<string>", line 82, in get_c_extension_status
        File "/tmp/pip-build-env-4kc5sz45/overlay/lib/python3.13/site-packages/setuptools/_distutils/ccompiler.py", line 787, in link_executable
          self.link(
          ~~~~~~~~~^
              CCompiler.EXECUTABLE,
              ^^^^^^^^^^^^^^^^^^^^^
          ...<11 lines>...
              target_lang,
              ^^^^^^^^^^^^
          )
          ^
        File "/tmp/pip-build-env-4kc5sz45/overlay/lib/python3.13/site-packages/setuptools/_distutils/unixccompiler.py", line 289, in link
          raise LinkError(msg)
      distutils.errors.LinkError: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Attempting to install rpy2 using conda:

(pyr) kjb3@kjb3-lm:~$ conda install rpy2
Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: - warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package rpy2-2.8.5-py27r3.3.2_0 requires python 2.7*, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.13.* , which can be installed;
└─ rpy2 is not installable because there are no viable options
   ├─ rpy2 [2.8.5|2.8.6] would require
   │  └─ python [2.7* |>=2.7,<2.8.0a0 ], which conflicts with any installable versions previously reported;
   ├─ rpy2 [2.8.5|2.9.1|2.9.2|2.9.3|2.9.4] would require
   │  └─ python [3.5* |>=3.5,<3.6.0a0 ], which conflicts with any installable versions previously reported;
   ├─ rpy2 [2.8.5|2.9.1|2.9.2|2.9.3] would require
   │  └─ python 3.6* , which conflicts with any installable versions previously reported;
   ├─ rpy2 [2.9.4|3.1.0|...|3.4.5] would require
   │  └─ python >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
   ├─ rpy2 [2.9.4|3.1.0|...|3.5.1] would require
   │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
   ├─ rpy2 [3.1.0|3.3.2|...|3.5.9] would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   ├─ rpy2 [3.3.2|3.3.6|...|3.5.9] would require
   │  └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
   ├─ rpy2 [3.4.5|3.5.1|...|3.5.9] would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   ├─ rpy2 [3.5.1|3.5.10|...|3.5.9] would require
   │  └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;
   └─ rpy2 3.5.11 would require
      └─ python >=3.12,<3.13.0a0 , which conflicts with any installable versions previously reported.

(pyr) kjb3@kjb3-lm:~$

**Comment by kburchfiel** [comment]
Actually, after rebooting my computer, I was able to use the pip command successfully. (I had just installed R as well, so maybe a reboot was required in order for the pip command to work.)

**Comment by lgautier** [comment]
Good. That part suggests that something was very outdated:

> ```
> package rpy2-2.8.5-py27r3.3.2_0 requires python 2.7*, but none of the providers can be installed
> ```
