### ISSUE TITLE
can't install rpy2

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#124]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/114) by Unknown (Bitbucket: [phillip_feldman](https://bitbucket.org/phillip_feldman), ).**

----------------------------------------

When I try to install Rpy2 (whether via easy_install or pip), I get errors (see below).  I have a 64-bit Windows 7 machine running Python 2.7.

Phillip

C:\Phillip\Computer\Python\Install>pip install rpy2
Downloading/unpacking rpy2
  Running setup.py egg_info for package rpy2

    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "c:\users\s117250\appdata\local\temp\1\pip-build\rpy2\setup.py", line 463, in <module>
        'rpy2': ['doc/source/rpy2_logo.png', ]}
      File "C:\Python27\lib\distutils\core.py", line 152, in setup
        dist.run_commands()
      File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 14, in replacement_run
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 254, in find_sources
        mm.run()
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 308, in run
        self.add_defaults()
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 332, in add_defaults
        sdist.add_defaults(self)
      File "C:\Python27\lib\site-packages\setuptools\command\sdist.py", line 191, in add_defaults
        build_ext = self.get_finalized_command('build_ext')
      File "C:\Python27\lib\distutils\cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Python27\lib\distutils\cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "c:\users\s117250\appdata\local\temp\1\pip-build\rpy2\setup.py", line 163, in finalize_options
        config += get_rconfig(r_home, about)
      File "c:\users\s117250\appdata\local\temp\1\pip-build\rpy2\setup.py", line 333, in get_rconfig
        rc = RConfig.from_string(rconfig, allow_empty = allow_empty)
      File "c:\users\s117250\appdata\local\temp\1\pip-build\rpy2\setup.py", line 293, in from_string
        + '\nin string\n' + string)
    ValueError: Invalid substring

    in string

    Complete output from command python setup.py egg_info:
    running egg_info

writing pip-egg-info\rpy2.egg-info\PKG-INFO

writing top-level names to pip-egg-info\rpy2.egg-info\top_level.txt

writing dependency_links to pip-egg-info\rpy2.egg-info\dependency_links.txt

warning: manifest_maker: standard file '-c' not found

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "c:\users\s117250\appdata\local\temp\1\pip-build\rpy2\setup.py", line 463, in <module>

    'rpy2': ['doc/source/rpy2_logo.png', ]}

  File "C:\Python27\lib\distutils\core.py", line 152, in setup

    dist.run_commands()

  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "<string>", line 14, in replacement_run

  File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 254, in find_sources

    mm.run()

  File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 308, in run

    self.add_defaults()

  File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 332, in add_defaults

    sdist.add_defaults(self)

  File "C:\Python27\lib\site-packages\setuptools\command\sdist.py", line 191, in add_defaults

    build_ext = self.get_finalized_command('build_ext')

  File "C:\Python27\lib\distutils\cmd.py", line 312, in get_finalized_command

    cmd_obj.ensure_finalized()

  File "C:\Python27\lib\distutils\cmd.py", line 109, in ensure_finalized

    self.finalize_options()

  File "c:\users\s117250\appdata\local\temp\1\pip-build\rpy2\setup.py", line 163, in finalize_options

    config += get_rconfig(r_home, about)

  File "c:\users\s117250\appdata\local\temp\1\pip-build\rpy2\setup.py", line 333, in get_rconfig

    rc = RConfig.from_string(rconfig, allow_empty = allow_empty)

  File "c:\users\s117250\appdata\local\temp\1\pip-build\rpy2\setup.py", line 293, in from_string

    + '\nin string\n' + string)

ValueError: Invalid substring

in string

----------------------------------------
Command python setup.py egg_info failed with error code 1 in c:\users\s117250\appdata\local\temp\1\pip-build\rpy2
Storing complete log in C:\Users\s117250\pip\pip.log

**Comment by lgautier** [comment]
Outdated.
