### ISSUE TITLE
Cannot install rpy2 3.2.4 with Python 3.5

### ISSUE THREAD

**Issue by bienvenu** [rpy2/rpy2#356]
I have read the discussion surrounding https://bitbucket.org/rpy2/rpy2/issues/580/installing-rpy2-on-travis-with-pip.

What is not clear to me however, is whether the current version of rpy2 is supposed to work with Python 3.5. In particular, looking at line 5 of `setup.py`, I see that "rpy2 is no longer supporting Python < 3.5.", suggesting that it should support Python 3.5.

Nevertheless, trying to upgrade rpy2 with pip I run into:
```
$ python3 --version
Python 3.5.3
$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
$ pip3 install --upgrade rpy2
Collecting rpy2
  Using cached https://files.pythonhosted.org/packages/62/bc/d43df0d9e96a38985a97d1cbdb5722e10cd8fa0da45686972f0b8fd18a67/rpy2-3.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jzkrjqtr/rpy2/setup.py", line 21, in <module>
        from rpy2 import situation
      File "/tmp/pip-build-jzkrjqtr/rpy2/rpy2/situation.py", line 98
        raise ValueError(f'The system {system} is currently not supported.')
                                                                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jzkrjqtr/rpy2/
```

Any idea?

**Comment by lgautier** [comment]
Python 3.5 is no longer supported.
