### ISSUE TITLE
reticulate + rpy2 sharing R process

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#470]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/456) by NV (Bitbucket: [nickdsc](https://bitbucket.org/nickdsc), GitHub: [nickdsc](https://github.com/nickdsc)).**

----------------------------------------

Cannot get to work `rpy2` v 2.9.2 and `reticulate` v 1.6 with R v 3.4.3 and Python 3.5.5 (or 3.6.5) to share the same instance of R embedded process / engine instance.

context - reviewed these but still cannot make this work
https://github.com/rstudio/reticulate/issues/98
https://github.com/rstudio/reticulate/pull/104
https://github.com/rstudio/reticulate/issues/138

Environment
```
$ uname -a
Linux bigdata-vm 4.4.0-83-generic rpy2/rpy2#116-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Python and R setup with `conda` `environment.yml`

```
name: dev-ds
channels:
- r
- conda-forge
- anaconda 
- defaults
dependencies:
- conda-forge::python=3.5.5
- conda-forge::numpy=1.14.2
- conda-forge::pandas=0.22.0
# ==============
# R core
# ==============
- r-base=3.4.3
- r-magrittr=1.5
- r-reticulate    # is 1.3 but need 1.6* so re-installed manually from R
- r-dplyr=0.7.4
- r-dbi=0.7
- r-r6=2.2.2
- r-magrittr=1.5
- r-jsonlite=1.5
- r-dplyr=0.7.4
- r-purrr=0.2.4
- r-bindr=0.1
# ==============
# R application runtime 
# ==============
- r-readr=1.1.1
- r-config=0.2
- r-xml
- r-reshape2
- r-data.table
- r-forecast=8.2
- r-tseries
- nlopt
- r-nloptr=1.0.4
# ==============
# R application dev
# ==============
- r-git2r     # 0.20.0
- r-rcpp=0.12.14 # 0.12.16
- r-devtools=1.13.4
- r-testthat=2.0.0
- r-roxygen2
- r-sparklyr  # 0.7.0

# ==============
# Python core
# ==============
- pip:
  - rpy2==2.9.2 
```
Using R from under the `conda`  env:

```
library(reticulate)
reticulate::import("sys")
rpy2 <- import('rpy2')
robjects <- import('rpy2.robjects')
```
exists with _"R is already initialized"_ caused by last line.

From a Python script `some.py`

```
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr
import rpy2.robjects as robjects

def main():
    r = robjects.r

    x = robjects.IntVector(range(10))
    y = r.rnorm(10)

    import os, sys
    os.environ['RETICULATE_PYTHON'] = sys.executable

    robjects.r('library("reticulate")')
    robjects.r('reticulate::import("sys")')

    nested = robjects.r('''
    nested <- function() {
    
        library(reticulate)
        use_condaenv("dev-ds")
            
        reticulate::import("sys")
        robjects <- import('rpy2.robjects')
        robjects$r('R.version')  
     
        return (1)
    }
        
    nested       
    ''')

    n = nested()

    print(n)

if __name__ == "__main__":
    main()
```

getting this 

```
.../bin/python/conda3/envs/dev-ds/lib/python3.5/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: 2: package ‘reticulate’ was built under R version 3.4.3 

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File ".../some.py", line 63, in <module>
    main()
  File ".../some.py", line 40, in main
    robjects.r('reticulate::import("sys")')
  File "/.../bin/python/conda3/envs/dev-ds/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/../bin/python/conda3/envs/dev-ds/lib/python3.5/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/.../bin/python/conda3/envs/dev-ds/lib/python3.5/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ImportError: 'rpycall' is not a built-in module

Detailed traceback: 
  File "/development/bin/python/conda3/envs/dev-ds/lib/R/library/reticulate/python/rpytools/call.py", line 2, in <module>
    import rpycall

Segmentation fault (core dumped)

```

Please see conversation on https://github.com/rstudio/reticulate/issues/208

**Comment by lgautier** [comment]
rpy2 and reticulate are now expected to work together without crashing.
