### ISSUE TITLE
Crash in rpy_classic.seq2vec for empty list

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#471]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/457) by Irwin Jungreis (Bitbucket: [iljungr](https://bitbucket.org/iljungr), GitHub: [iljungr](https://github.com/iljungr)).**

----------------------------------------

When an empty list is passed to rpy_classic.seq2vec it crashes with "UnboundLocalError: local variable 'vec' referenced before assignment".
(Happens to me in 2.8.6 but the code has the same bug in 2.9.2. I need a fix in 2.8 because I can't install Python 3 yet.)

For example:

```
#!python
import rpy2.rpy_classic as rpy
rpy.set_default_mode(rpy.BASIC_CONVERSION) # Happens either way
rpy.r.X11()
rpy.r.plot([], xlim = [0,1], ylim=[0,1])

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "//anaconda/lib/python2.7/site-packages/rpy2/rpy_classic.py", line 272, in __getattr__
    res = self.__getitem__(name)
  File "//anaconda/lib/python2.7/site-packages/rpy2/rpy_classic.py", line 279, in __getitem__
    res = rpy2py(res)
  File "//anaconda/lib/python2.7/site-packages/rpy2/rpy_classic.py", line 186, in rpy2py
    raise ValueError("Invalid default mode.")
ValueError: Invalid default mode.
```

**Comment by lgautier** [comment]
Just a note while transferring issues along with the rest of the project to Github: the legacy rpy mode should not be relied on. There has not been an rpy release in a decade, and I don't seen any effort going toward anything else than removing from rpy2 anything rpy-related.

**Comment by lgautier** [comment]
`rpy_classic` is long gone.
