### ISSUE TITLE
Test failures while packaging

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#502]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/488) by Timo Kaufmann (Bitbucket: [timokau](https://bitbucket.org/timokau), GitHub: [timokau](https://github.com/timokau)).**

----------------------------------------

Hi,

I'm trying to make the rpy2 nix package usable. Up until now, tests where disabled. This is *not* an issue with rpy2 itself, but likely a packaging issue. However I am hoping that you can point me into the right direction as to what may be the issue.

The two remaining failures are:

```
/nix/store/yazzil8pqk3qaw9jqd2l6rbhmczlgz58-python3.6-rpy2-2.9.4/lib/python3.6/site-packages/rpy2/robjects/lib/dplyr.py:24: UserWarning: This was designed againt dplyr version 0.7.5 but you have 0.7.6
  warnings.warn('This was designed againt dplyr version %s but you have %s' % (TARGET_VERSION, dplyr.__version__))
/nix/store/yazzil8pqk3qaw9jqd2l6rbhmczlgz58-python3.6-rpy2-2.9.4/lib/python3.6/site-packages/rpy2/robjects/lib/ggplot2.py:67: UserWarning: This was designed againt ggplot2 version 2.2.1 but you have 3.0.0
  warnings.warn('This was designed againt ggplot2 version %s but you have %s' % (TARGET_VERSION, ggplot2.__version__))
..................................................................................................................................s..............................................F..E...............................>
................................................x..........................................ssssssssssssss..........................................................................................................s>
======================================================================
ERROR: testArrayStructComplex (rinterface.tests.test_SexpVectorNumeric.SexpVectorNumericTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/yazzil8pqk3qaw9jqd2l6rbhmczlgz58-python3.6-rpy2-2.9.4/lib/python3.6/site-packages/rpy2/rinterface/tests/test_SexpVectorNumeric.py", line 52, in testArrayStructComplex
    nx = self.numericmodule.asarray(x)
  File "/nix/store/3mg1dsp809pn371d7pjgjqjczlrs9yi3-python3.6-numpy-1.15.2/lib/python3.6/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
RuntimeError: Item size 16 for PEP 3118 buffer format string B does not match the dtype B item size 1.

======================================================================
FAIL: testUTF8params (rinterface.tests.test_SexpClosure.SexpClosureTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/yazzil8pqk3qaw9jqd2l6rbhmczlgz58-python3.6-rpy2-2.9.4/lib/python3.6/site-packages/rpy2/rinterface/tests/test_SexpClosure.py", line 39, in testUTF8params
    self.assertEqual(u'\u54c8\u54c8', res.do_slot("names")[0])
AssertionError: '\u54c8\u54c8' != '<U+54C8><U+54C8>'
- \u54c8\u54c8
+ <U+54C8><U+54C8>


----------------------------------------------------------------------
Ran 438 tests in 6.796s

FAILED (failures=1, errors=1, skipped=16, expected failures=1)
rpy2 version: 2.9.4
- built against R version: 3-5.1--74947
- running linked to R version: R version 3.5.1 (2018-07-02)
```

**Comment by lgautier** [comment]
No longer fails.
