### ISSUE TITLE
Importing `rpy2` before `scipy` leads to segfaults

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#505]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/491) by Timo Kaufmann (Bitbucket: [timokau](https://bitbucket.org/timokau), GitHub: [timokau](https://github.com/timokau)).**

----------------------------------------

Sorry for opening so many tickets here :)

Previously reported to `scipy` here: https://github.com/scipy/scipy/issues/9466

Apparently `lapack` always segfaults on invalid inputs. `scipy` tries to gracefully handle this and not crash the python instance. However when importing `rpy2` before `scipy`, this does not work:

```python
$ python2 -c 'from rpy2 import rinterface as ri; ri.initr(); import scipy.linalg; scipy.linalg.schur(scipy.empty(shape=[0,0]))'
/nix/store/5wc1ck1rbsxrrq841ji9d0q2q34l5lvv-python-2.7.15-env/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:195: RRuntimeWarning: Error: BLAS/LAPACK routine 'DGEES ' gave error code -6

  warnings.warn(x, RRuntimeWarning)
/nix/store/5wc1ck1rbsxrrq841ji9d0q2q34l5lvv-python-2.7.15-env/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:195: RRuntimeWarning: Fatal error: unable to initialize the JIT


  warnings.warn(x, RRuntimeWarning)
[1]    10167 segmentation fault  result/bin/python2 -c 
```

vs. without the import:

```python
$ python2 -c 'import scipy.linalg; scipy.linalg.schur(scipy.empty(shape=[0,0]))'
 ** On entry to DGEES PMGLRH parameter number  6 had an illegal value
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/5wc1ck1rbsxrrq841ji9d0q2q34l5lvv-python-2.7.15-env/lib/python2.7/site-packages/scipy/linalg/decomp_schur.py", line 162, in schur
    sort_t=sort_t)
_flapack.error: ((lwork==-1)||(lwork >= MAX(1,2*n))) failed for 3rd keyword lwork: dgees:lwork=0                            
```

When explicitly preloading `openblas` with `LD_PRELOAD` it also works when `rpy2` is imported first.

**Comment by dimpase** [comment]
I get the same error with "same" BLAS, too.

**Comment by lgautier** [comment]
Do you mean that you are getting the same error when using `LD_PRELOAD` ?

**Comment by dimpase** [comment]
No, I mean the same error with libR/rpy2  and scipy linked to the same (open)blas library.
scipy people wrote that they suspect that libR/rpy2 do some kind of non-standard initialisation of BLAS, which invalidates their method to avoid segfaults if BLAS is called with invalid arguments.

**Comment by lgautier** [comment]
That would be `libR.so` then. rpy2 is not direcrly doing anything with respect to BLAS initialiaztion.

**Comment by lgautier** [comment]
R can either link to a system's BLAS, or compile its own. If not paying to much attention to this at R build time you will end up with those local compiled libraries.

**Comment by dimpase** [comment]
I'm using an (lib)R build from the system, linked to lib(open)blas, and build Python3, rpy2 and scipy linked to lib(open)blas and libR.
Note that libblas is the same as libopenblas (both are symbolic links to the same libopenblas)

```
$ ldd /usr/lib/R/lib/libR.so 
        linux-vdso.so.1 (0x00007ffdd71fa000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007c1629326000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007c16291e0000)
        libreadline.so.8 => /usr/lib/libreadline.so.8 (0x00007c162918e000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007c162911b000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007c16290f3000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007c16290e0000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007c16290c4000)
        libtirpc.so.3 => /usr/lib/libtirpc.so.3 (0x00007c1629095000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007c1629090000)
        libicuuc.so.65 => /usr/lib/libicuuc.so.65 (0x00007c1628eae000)
        libicui18n.so.65 => /usr/lib/libicui18n.so.65 (0x00007c1628bba000)
        libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007c1628b81000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007c1628b5d000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007c1628996000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007c162aa0d000)
        libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007c1628927000)
        libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007c16288d7000)
        libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007c16287ea000)
        libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007c16287b6000)
        libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007c16287ae000)
        libicudata.so.65 => /usr/lib/libicudata.so.65 (0x00007c1626cfd000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007c1626b13000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007c1626af9000)
        libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007c1626aea000)
        libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007c1626ae1000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007c1626ac8000)

$ ldd local/lib/python3.7/site-packages/rpy2/rinterface/_rpy_device.cpython-37m-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffc613f1000)
        libreadline.so.8 => /usr/lib/libreadline.so.8 (0x00007bf13d8f2000)
        libR.so => /usr/lib64/R/lib/libR.so (0x00007bf13d458000)
        libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x00007bf13d3c7000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007bf13d354000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007bf13d32c000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007bf13d319000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007bf13d2fd000)
        libtirpc.so.3 => /usr/lib/libtirpc.so.3 (0x00007bf13d2ce000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007bf13d2c3000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007bf13d2be000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007bf13d178000)
        libicuuc.so.65 => /usr/lib/libicuuc.so.65 (0x00007bf13cf96000)
        libicui18n.so.65 => /usr/lib/libicui18n.so.65 (0x00007bf13cca0000)
        libpython3.7m.so.1.0 => /home/dimpase/sagetrac-mirror/local/lib/libpython3.7m.so.1.0 (0x00007bf13c95e000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007bf13c797000)
        libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007bf13c728000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007bf13b4ea000)
        libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007bf13b4b1000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007bf13b48d000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007bf13d95f000)
        libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007bf13b43d000)
        libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007bf13b350000)
        libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007bf13b31c000)
        libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007bf13b316000)
        libicudata.so.65 => /usr/lib/libicudata.so.65 (0x00007bf139863000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007bf139679000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007bf13965f000)
        libcrypt.so.1 => /usr/lib/libcrypt.so.1 (0x00007bf139625000)
        libutil.so.1 => /usr/lib/libutil.so.1 (0x00007bf139620000)
        libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007bf13960f000)
        libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007bf139608000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007bf1395ef000)

$ ldd local/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007fffcc5cd000)
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007b1ba48c5000)
        libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007b1ba48a9000)
        libopenblas.so.3 => /usr/lib/libopenblas.so.3 (0x00007b1ba366b000)
        libpython3.7m.so.1.0 => /home/dimpase/sagetrac-mirror/local/lib/libpython3.7m.so.1.0 (0x00007b1ba3329000)
        libgfortran.so.5 => /usr/lib/libgfortran.so.5 (0x00007b1ba3089000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007b1ba2f43000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007b1ba2f27000)
        libquadmath.so.0 => /usr/lib/libquadmath.so.0 (0x00007b1ba2edc000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007b1ba2d15000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007b1ba2cf3000)
        libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007b1ba2cba000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007b1ba5050000)
        libcrypt.so.1 => /usr/lib/libcrypt.so.1 (0x00007b1ba2c80000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007b1ba2c79000)
        libutil.so.1 => /usr/lib/libutil.so.1 (0x00007b1ba2c74000)
```

**Comment by dimpase** [comment]
And the order of imports matters, as above:

* this gives a segfault:
```
Python 3.7.3 (default, Jan 24 2020, 20:16:50) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpy2.robjects
>>> import scipy.linalg  
>>> scipy.linalg.schur(scipy.empty(shape=[0,0])) 
 ** On entry to DGEES parameter number  6 had an illegal value
```
* and this does not
```
Python 3.7.3 (default, Jan 24 2020, 20:16:50) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.linalg
>>> import rpy2.robjects
>>> scipy.linalg.schur(scipy.empty(shape=[0,0]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dimpase/sagetrac-mirror/local/lib/python3.7/site-packages/scipy/linalg/decomp_schur.py", line 139, in schur
    result = gees(lambda x: None, a1, lwork=-1)
ValueError: On entry to DGEES parameter number 6 had an illegal value
>>> 
```

**Comment by dimpase** [comment]
@timokau - have you ever mentioned this problem on sage-devel or other sagemath-related place?

**Comment by timokau** [comment]
@dimpase the issue originated here: https://trac.sagemath.org/ticket/26596#comment:21

**Comment by lgautier** [comment]
I just tried the foilowing two options without getting a segfault.

```python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpy2.robjects
>>> import scipy.linalg
>>> scipy.linalg.schur(scipy.empty(shape=[0,0])) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/py36_env/lib/python3.6/site-packages/scipy/linalg/decomp_schur.py", line 139, in schur
    result = gees(lambda x: None, a1, lwork=-1)
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)
```

```python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.linalg
>>> import rpy2.robjects
>>> scipy.linalg.schur(scipy.empty(shape=[0,0]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/laurent/Desktop/software/python/py36_env/lib/python3.6/site-packages/scipy/linalg/decomp_schur.py", line 139, in schur
    result = gees(lambda x: None, a1, lwork=-1)
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)
>>> 

```

```python
>>> rpy2.__version__
'3.3.0.dev'
>>> scipy.__version__
'1.3.2'
```

**Comment by dimpase** [comment]
The segfault only happens in very particular configurations of blas/cblas,
e.g. the one on the current Archlinux.

**Comment by lgautier** [comment]
Ah.
This may mean the issue is outside of rpy2 then.

**Comment by dimpase** [comment]
Well, on the other hand it may be argued that it's rpy2 that is apparently "spoiling" `blas` so that a next module linking `blas` gets problems. 

Could you perhaps explain how `blas` is initialised by rpy2? If you check scipy's dicscussion,  they said it could be something to do with a JIT mechanism of R (or rpy2 ?): cf
https://github.com/scipy/scipy/issues/9466#issuecomment-437680836

**Comment by lgautier** [comment]
Well, since `rpy2` is merely linking to R's shared library I guess the bucket is therefore passed to R ?

I have the recollection of saying it earler but `rpy2` is not initializing `blas`, at least not directly. All it does is initialize R.

**Comment by lgautier** [comment]
R not being a good neighbor inadvertently would not be a complete surprise. I had a similar problem (as in segfault depending on import order) to track for rpy2 and it turned out that `libreadline` initialized in a way that did not consider that it could be reinitialized with different setting.

**Comment by dimpase** [comment]
Could you point out where this libreadline problem has been handled?

**Comment by lgautier** [comment]
There is this: https://github.com/rpy2/rpy2/commit/eb2744e9566934f449402add1d4c7fa623a2d78b

This was mostly promptly handled in Python's source after I pointed out the issue. The issue could be see as both attributable to Python or R use of readline. I did not much success in getting that fixed on the R side.

**Comment by lgautier** [comment]
The segfault appears to be gone (Python 3.10, R-4.2, rpy2-3.5.10, scipy-1.23.1)
