### ISSUE TITLE
LookupError: 'show' not found -  in PyCharm IDE

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#515]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/501) by Allan Campopiano (Bitbucket: [Alcampopiano](https://bitbucket.org/Alcampopiano), GitHub: [Alcampopiano](https://github.com/Alcampopiano)).**

----------------------------------------

Hi Laurent,

I spent a couple days here trying to understand the problem but haven't succeeded.

The following works perfectly in a python/ipython console, but not in the PyCharm IDE. I'm wondering if you have any insight into what could be happening. 

### create conda environment ###

```
#!bash
conda create --name test_env
conda install -c r r-base
conda install -c r rpy2
conda activate test_env
```

### within PyCharm ###
```
#!python
import rpy2
import rpy2.robjects as robjects

Traceback (most recent call last):
  File "/home/allan/anaconda3/envs/test_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-ac406b5f454c>", line 2, in <module>
    import rpy2.robjects as robjects
  File "/snap/pycharm-community/103/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/allan/anaconda3/envs/test_env/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 19, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/snap/pycharm-community/103/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/allan/anaconda3/envs/test_env/lib/python3.7/site-packages/rpy2/robjects/robject.py", line 52, in <module>
    class RObjectMixin(object):
  File "/home/allan/anaconda3/envs/test_env/lib/python3.7/site-packages/rpy2/robjects/robject.py", line 66, in RObjectMixin
    __show = rpy2.rinterface.baseenv.get("show")
LookupError: 'show' not found

```

### Checking rpy2.objects from python console (within my environment) ###

```
#!python
print(rpy2.robjects.r) 
.
.
.
version.string: R version 3.5.1 (2018-07-02)
```

As far as I can tell, I do not have any other versions of R or rpy2 on my system, other than in this environment. I'm using rpy2 version 2.9.1. 

Any help would be greatly appreciated. 

Allan

**Comment by Zhenyu-Guo** [comment]
Thank you for your help with this issue. My problem has been resolved, and I really appreciate your assistance.
