### ISSUE TITLE
Cannot use rpy2 in MacOS Mojave

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#517]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/503) by Nick Mancuso (Bitbucket: [Nicholas Mancuso](https://bitbucket.org/Nicholas Mancuso), ).**

----------------------------------------

I am having trouble getting rpy2 to work with my R 3.4.3 installation on Mac Mojave.

I was able to "install" rpy2 with pip3 without error, but when I try to import anything I get an error. Here is an example 

```
#!python

python3 -m 'rpy2.tests'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/tests.py", line 23, in <module>
    import rpy2.tests_rpy_classic
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/tests_rpy_classic.py", line 3, in <module>
    import rpy2.rpy_classic as rpy
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rpy_classic.py", line 5, in <module>
    import rpy2.rinterface as ri
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface/__init__.py", line 51, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface/_rinterface.cpython-37m-darwin.so, 2): Library not loaded: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libR.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface/_rinterface.cpython-37m-darwin.so
  Reason: image not found
```

I would love to be able to use this library for some of my projects, but cannot figure out what is going on here.

rpy2 version: 2.9.5
Python version: 3.7.0
R version: 3.4.3
Mac OS: 10.14 Mojave

**Comment by lgautier** [comment]
rpy2 is working with MacOS. Building on ARM (M1 and M2) is left to the user but is reported to be working.
