### ISSUE TITLE
Redesign converter architecture

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#539]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/525) by Philipp A. (Bitbucket: [flyingsheep](https://bitbucket.org/flyingsheep), GitHub: [flyingsheep](https://github.com/flyingsheep)).**

----------------------------------------

Converters are unobvious, depend on global state, and have implicit dependencies that are not enforced.

Converters have a hard job: They need to do convert stuff reliably, but they also need to pass conversion over to other activated converters when necessary (e.g. dict keys and values can be of any type)

Inside of converter functions, you can’t be sure which ones are activated, so you can’t expect anything from the return value of eg. `conversion.py2rpy`. Converters do expect that however:

```python
>>> import pandas as pd
>>> from rpy2.robjects import pandas2ri
>>> pandas2ri.py2rpy(pd.DataFrame(dict(a=[1,2])))
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py", line 56, in py2rpy_pandasdataframe
    od[name] = conversion.py2rpy(values)
  File "/usr/lib/python3.7/functools.py", line 824, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/lib/python3.7/site-packages/rpy2/robjects/conversion.py", line 60, in _py2rpy
    str(type(obj))
NotImplementedError: Conversion 'py2rpy' not defined for objects of type '<class 'pandas.core.series.Series'>'
```

Furthermore, converters can’t “give up” and let another registered different converter take over. E.g. a converter for `SexpS4` should be able to say “OK, I can only handle S4 objects with `'Foo' in obj.rclass`, let other converters that can handle other S4 classes try their luck.”

---

I think a solution contains a converter hierarchy that can be invoked (to have reliably results, e.g. for pandas which invokes numpy), in addition to invoking the active converter (for generic conversion without expectations on the results, e.g. dicts), and a more fine-grained dispatch than only on the type (maybe simply a marker object that means “I can’t actually handle this”)

**Comment by lgautier** [comment]
Trying to resurrect this. I am writing this also make it clear to myself. I might not get this right the first time around.

In short, the situation is: 

- While all R objects are C struct pointers `SEXP`, they also have a type (class) at the C level (R's C API).
- Python classes map this types (with an added inheritance hierarchy compared to R's C types)
- That type will decide which type-specific C function are mapped to Python methods (calling the wrong C function on an incompatible C object may result in a segfault otherwise.
- All the above is the `rpy2.rinterface` / `rpy2.rinterface_lib`.

In addition to that:

- At the R language level, R objects can follow various OOP systems (either S3, S4, R6, etc...). If S4, there is a indication at the C level that this is an S4 object but the class hierarchy it belongs to is an R-level contruct
- Such "higher-level" objects are mapped at the `rpy2.robjects` level, with an conversion system intended to be user-configurable.
- The current system is using `singledispatch` to go from a Python class to an `robjects` or `rinterface` level class, or the other way around.
- The duality, or even multiplicity, of OOP systems between R's C API, and the R-language level create a situation where the conversion needs to be resolved within a dispatch function. This is problematic when we want to dynamically want to change the conversion and might not know all possible conversion when writing the rpy2 code base.  
- Limitations in `singledispatch` do not allow to remove a dispatch once added
-

**Comment by lgautier** [comment]
- S4 objects have a C-level type, so isolating them in a separate conversion sub-system might be the most practical.
- S3, or R6, or any other possible alternative OOP might be trickier because:
  - The `class` attribute may define whether a object is part of a class hierarchy or OOP, or just a base R object.
  - R lets users add, modify, or remove that attribute for any object (care must be taken to prevent the wrong C-level type mapping)
  - Because of the above the dispatch has to consider both the C-level and the `class` attribute when converting from R
  - It might only be possible to support, say, S3 and R6 but not be able to ensure that it would work out of the box for additional OOP system 
- Conversion might require to be able to dispatch on source (the objects fed to the conversion) as well as on destination.

**Comment by lgautier** [comment]
Thinking more about this, it seems that 2 concept are conflated in the current conversion design:
- mapping: the objects in R (or Python) is made accessible to Python (or R, respectively) through a proxy
- casting: the object in R (or Python) is translated with its content copied to Python (or R, respectively)

It might be worthwhile to disentangle that, or give more explicitly control over which one is used for a given object,

**Comment by lgautier** [comment]
The conversion system was (partly) redesigned to accommodate better dispatch in the R -> Py direction by allowing rules based on the R class (rather than only the R base / C-level types).
