### ISSUE TITLE
import rpy2.interactive as r fails on rpy2 (versions 3.0+)

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#556]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/542) by Michał Krassowski (Bitbucket: [krassowski](https://bitbucket.org/krassowski), GitHub: [krassowski](https://github.com/krassowski)).**

----------------------------------------

According to the documentation, `rpy2.interactive` is [being deprecated](https://rpy2.github.io/doc/latest/html/interactive.html#utilities-for-interactive-work), however the docs suggest that it should still work in the latest versions. Using Python 3.7.2 and Python 3.7.3 I tested importing it with following versions of rpy2: 2.9.4, 3.0.0, 3.0.1, 3.0.2. The import worked only on 2.9.4 and resulted in the same error with newer versions:

```python
>>> import rpy2.interactive as r
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/rpy2/interactive/__init__.py", line 26, in <module>
    from . import process_revents as revents
  File "/usr/local/lib/python3.7/dist-packages/rpy2/interactive/process_revents.py", line 6, in <module>
    from rpy2.rinterface import process_revents
ImportError: cannot import name 'process_revents' from 'rpy2.rinterface' (/usr/local/lib/python3.7/dist-packages/rpy2/rinterface.py)
```

I use Ubuntu 19.04, tested using both system-wide Python install and an isolated virtual environment. R 3.5.2 \(2018-12-20\).

It’s not a big issue for me, though I wanted to let you know of the problem \(a circular import might be the culprit\).

Thank you for your time and development of this awesome package!

‌

PS. Some context: I am trying to get a way to show an interactive progress bar in Jupter with rpy2 extension \(or any interactive output really\). I’ve created a question at StackOverflow: [How to get interactive R output in Jupyter \(IPython, rpy2\), e.g. for a progress bar?](https://stackoverflow.com/questions/55986202/how-to-get-interactive-r-ouput-in-jupyter-ipython-rpy2-e-g-for-a-progress-b) and also attempted to use callbacks to get a progress bar on the Python side \(`rpy2.rinterface_lib.callbacks.consolewrite_print`, and `rpy2.rinterface_lib.callbacks.consoleflush`\) but these only seem to trigger when using the rinterface, but not for the code run via Jupyter magic. Before I’ve _succeeded_ with calling the code via `robjects.r` I've tried to use the `interactive.r`, hoping it would do a better job. I would appreciate your input on this as well!

**Comment by lgautier** [comment]
The code example reported in the issue works with the current dev branch. Closing.
