### ISSUE TITLE
rpy2 importr Error: Cannot import any packages

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#580]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/566) by Charles Marx (Bitbucket: [Charles Marx](https://bitbucket.org/Charles Marx), ).**

----------------------------------------

rpy2 has recently been raising an internal `TypeError: 'ExprSexpVector' object is not callable` error when I import any package using the `importr` function from rpy2. Even the most simple sample code from the rpy2 documentation fails to run \(code below\).

```
from rpy2.robjects.packages import importr
utils = importr("utils")
```

Instead of loading the r package, the second line raises the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/packages.py", line 492, in importr
    symbol_check_after=symbol_check_after)
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/packages.py", line 204, in __init__
    self.__fill_rpy2r__(on_conflict=on_conflict)
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/packages.py", line 330, in __fill_rpy2r__
    .__fill_rpy2r__(on_conflict=on_conflict))
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/packages.py", line 264, in __fill_rpy2r__
    rpyobj = conversion.rpy2py(riobj)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/functools.py", line 827, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 207, in _rpy2py_sexpclosure
    return SignatureTranslatedFunction(obj)
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 163, in __init__
    formals.names,
  File "/usr/local/lib/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", line 180, in names
    return embedded.globalenv.find('names')(self)
TypeError: 'ExprSexpVector' object is not callable
```

‌

My work is quite dependent on rpy2 at the moment, so any solution or workaround would be greatly appreciated. 

SOFTWARE:

* python 3.7.3
* rpy2 3.0.5 \(installed via pip\)
* MacOS Mojave 10.14.4
* R 3.6.1 \(recently reinstalled in attempt to fix this problem\)

The error was not happening when I was writing with rpy2 about 2 months ago. I work with R daily still and have not encountered any problems when working with R directly.

[https://stackoverflow.com/questions/57058759/rpy2-importr-error-cannot-import-any-packages](https://stackoverflow.com/questions/57058759/rpy2-importr-error-cannot-import-any-packages)

**Comment by lgautier** [comment]
No other report of the issue since, and the conversation pointing toward system/software on the user's system at the root of the issue.
