### ISSUE TITLE
mstl function in forecast package gives error

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#599]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/586) by Nils Holgersson (Bitbucket: [Nils Holgersson](https://bitbucket.org/Nils Holgersson), ).**

----------------------------------------

When running the mstl function from the forecast package in R I am getting the following error:

‌

```
R[write to console]: Error in `[.default`(x, , 1) : incorrect number of dimensions

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 14, in forecast
  File "/Users/ejohara/sandbox/python_envs/yuntao/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 192, in __call__
    .__call__(*args, **kwargs))
  File "/Users/ejohara/sandbox/python_envs/yuntao/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 121, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/Users/ejohara/sandbox/python_envs/yuntao/lib/python3.6/site-packages/rpy2/rinterface_lib/conversion.py", line 28, in _
    cdata = function(*args, **kwargs)
  File "/Users/ejohara/sandbox/python_envs/yuntao/lib/python3.6/site-packages/rpy2/rinterface.py", line 785, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in `[.default`(x, , 1) : incorrect number of dimensions
```

All other forecast methods in the forecast package seem to work, so I am not sure why this one fails.

I am running rpy2 version 3.1.0 on Mac OS, R version 3.5.2.

‌

The following code can be run to recreate this issue:

‌

```python
import rpy2.robjects as robjects
import numpy as np
import rpy2.robjects.numpy2ri
rpy2.robjects.numpy2ri.activate()

def forecast():
    robjects.r('''
        library(forecast)
        mstl_forec <- function(x, fh){
            data <- msts(x, seasonal.periods=c(24,168))
            model <- forecast::mstl(data)
            forecast::forecast(model, h=fh)$mean
        }
    ''')
    
    fh=24
    seriesdata = np.array(range(168*3))
    process_forecast_methods = robjects.r['mstl_forec']
    fcast = process_forecast_methods(x=seriesdata, fh=fh)
    return fcast 

res = forecast()
```

‌

‌

**Comment by lgautier** [comment]
I am not sure this is an issue with rpy2. This seems more like an operator error, in the sense the underlying R function called finds a parameter invalid. If truly the case, asking on a list or a place like StackOverflow might get more attention.

**Comment by lgautier** [comment]
Likely an operator error. Closing.
