### ISSUE TITLE
Install RPY2 on mac fails

### ISSUE THREAD

**Issue by tchaminaFR** [rpy2/rpy2#667]
Hello,

I am not a confirmed python coder so please bear with my naive comments.

I am trying to have rpy2 work on my mac (10.15.2) and fail to manage. I have python 3.7 installed as well as R 3.3 (see later *) and I am developping on pycharm. With this setup, I manage to run pip install rpy2 without error but nevertheless I get an error message when trying to import from rpy2. I'll give hereunder the error message:
* I first installed the latest version of R 3.5 but I couldn't run the installer though pip and found in a forum that it worked on an earlier version, and it did indeed: the install didn't bring any error message with 3.3)

Any help will be appreciated as I am seriously planning to make R with python my next platform for statistics! I did see a recent thread that seemed similar in the title (#613) but I couldn't understand the exact issue and the solution. 

Many thanks in advance!!
Thierry C.

import rpy2.robjects as robjects
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-31-c279966ca66e>", line 1, in <module>
    import rpy2.robjects as robjects
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 18, in <module>
    import rpy2.robjects.functions
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 6, in <module>
    from rpy2.robjects import help
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/robjects/help.py", line 40, in <module>
    quiet_require('tools')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/robjects/help.py", line 35, in quiet_require
    expr = rinterface.parse(expr_txt)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 40, in _
    cdata = function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface.py", line 46, in parse
    return _rinterface._parse(robj.__sexp__._cdata, num)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/_rinterface_capi.py", line 545, in _parse
    openrlib.rlib.R_tryCatchError(
ffi.error: symbol 'R_tryCatchError' not found in library '/Library/Frameworks/R.framework/Resources/lib/libR.dylib': dlsym(0x7ff2593b5070, R_tryCatchError): symbol not found

**Comment by tchaminaFR** [comment]
Please, any hint on where I could start digging to fix this issue, if possible. I really wanted to have this R/Python install running on my computer!

Thanks in advance, TC.

**Comment by bbgw** [comment]
This appears related with multiple installed versions of R. Worth try [uninstall](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Uninstalling-under-macOS)

**Comment by lgautier** [comment]
`R_tryCatchError` appeared in the R C API with R-3.5, IIRC. As pointed out above your system might pick up an older version installed on your system.

Try rpy2's diagnostic report:

```bash
python -m rpy2.situation
```

Otherwise R-3.5 is an older release (current is 4.0, previous was 3.6). Consider upgrading if you want to use a recent rpy2 version.

**Comment by tchaminaFR** [comment]
Thanks - it was simple but it seems to have done the trick! I'll have to try the package more thoroughly as soon as possible!

Thanks again, Thierry C.
