### ISSUE TITLE
cannot load library 'C:\Users\chpri\Anaconda3\lib\R\bin\x64\R.dll': error 0x7e

### ISSUE THREAD

**Issue by chpriya03** [rpy2/rpy2#721]
Hi,

When I am trying to import libraries of rpy2 I am facing below error

OSError Traceback (most recent call last)
in
----> 1 import pymer4

~\Anaconda3\lib\site-packages\pymer4_init_.py in
3 all = ["models", "utils", "simulate", "stats", "io", "version"]
4
----> 5 from .models import Lmer, Lm, Lm2
6 from .simulate import easy_multivariate_normal, simulate_lm, simulate_lmm
7

~\Anaconda3\lib\site-packages\pymer4\models_init_.py in
3 """
4
----> 5 from .Lmer import Lmer
6 from .Lm import Lm
7 from .Lm2 import Lm2

~\Anaconda3\lib\site-packages\pymer4\models\Lmer.py in
7
8 from copy import copy
----> 9 from rpy2.robjects.packages import importr
10 import rpy2.robjects as robjects
11 from rpy2.rinterface_lib import callbacks

~\Anaconda3\lib\site-packages\rpy2\robjects_init_.py in
14 from functools import partial
15 import types
---> 16 import rpy2.rinterface as rinterface
17 import rpy2.rlike.container as rlc
18

~\Anaconda3\lib\site-packages\rpy2\rinterface.py in
4 import typing
5 from typing import Union
----> 6 from rpy2.rinterface_lib import openrlib
7 import rpy2.rinterface_lib._rinterface_capi as _rinterface
8 import rpy2.rinterface_lib.embedded as embedded

~\Anaconda3\lib\site-packages\rpy2\rinterface_lib\openrlib.py in
42 rlib = _rinterface_cffi.lib
43 else:
---> 44 rlib = _dlopen_rlib(R_HOME)
45
46

~\Anaconda3\lib\site-packages\rpy2\rinterface_lib\openrlib.py in _dlopen_rlib(r_home)
35 raise ValueError('The library path cannot be None.')
36 else:
---> 37 rlib = ffi.dlopen(lib_path)
38 return rlib
39

OSError: cannot load library 'C:\Users\chpri\Anaconda3\lib\R\bin\x64\R.dll': error 0x7e

Also below is the output of rpy2.situation

(base) C:\Users\chpri>python -m rpy2.situation
rpy2 version:
3.3.2
Python version:
3.7.7 (default, May 6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
Looking for R's HOME:
Environment variable R_HOME: None
InstallPath in the registry: C:\Program Files\R\R-3.6.1
Environment variable R_USER: None
Environment variable R_LIBS_USER: None
R version:
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

In the PATH:
Loading R library from rpy2: cannot load library 'C:\Users\chpri\Anaconda3\lib\R\bin\x64\R.dll': error 0x7e
Additional directories to load R packages from:
None

Any help will be appreciated. Thank you.

**Comment by chpriya03** [comment]
Can you please help to solve this issue

**Comment by pavel-tarasov** [comment]
I faced same error, but I installed rpy2 via pip in venv.
Windows Server 2016 Standart
R-4.0.2
Python 3.8.3
Path contains C:\Program Files\R\R-4.0.2 and C:\Program Files\R\R-4.0.2\bin\x64
And there are environment variables: 
R_HOME=C:\Program Files\R\R-4.0.2
R_USER=pavelt
R_LIBS_USER=pavelt

When I'm trying to import rpy2.robjects I'm getting:
`import rpy2.robjects as robjects`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pavelt\Documents\Python\.rpy2_venv\lib\site-packages\rpy2\robjects\__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "C:\Users\pavelt\Documents\Python\.rpy2_venv\lib\site-packages\rpy2\rinterface.py", line 6, in <module>
    from rpy2.rinterface_lib import openrlib
  File "C:\Users\pavelt\Documents\Python\.rpy2_venv\lib\site-packages\rpy2\rinterface_lib\openrlib.py", line 44, in <module>
    rlib = _dlopen_rlib(R_HOME)
  File "C:\Users\pavelt\Documents\Python\.rpy2_venv\lib\site-packages\rpy2\rinterface_lib\openrlib.py", line 37, in _dlopen_rlib
    rlib = ffi.dlopen(lib_path)
OSError: cannot load library 'C:\Program Files\R\R-4.0.2\bin\x64\R.dll': error 0x7e


Also I'm getting same error when I'm trying to check situation via `python -m rpy2.situation`:
rpy2 version:
3.3.5
Python version:
3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
Looking for R's HOME:
    Environment variable R_HOME: C:\Program Files\R\R-4.0.2
    InstallPath in the registry: C:\Program Files\R\R-4.0.2
    Environment variable R_USER: pavelt
    Environment variable R_LIBS_USER: pavelt
R version:
    In the PATH: None
    Loading R library from rpy2: cannot load library 'C:\Program Files\R\R-4.0.2\bin\x64\R.dll': error 0x7e
Additional directories to load R packages from:
None
C extension compilation:
'sh' is not recognized as an internal or external command,
operable program or batch file.
    Warning: Unable to get R compilation flags.

I'm not sure if this problem is the same or I should create a new issue, but I hope anybody can help me.

**Comment by OnlyBelter** [comment]
Same error report!

**Comment by OnlyBelter** [comment]
I solved this error by using old version of `rpy2` (2.9.4) installed by conda:

`conda install rpy2`

**Comment by jakeLester66** [comment]
I have the same issue. Was using rpy2=3.3.2, Windows 10.

following @OnlyBelter decision and downgrading. Hope this gets fixed soon!

**Comment by paulmueller** [comment]
This seems to be a recurrent issue. I am trying to install via pip on appveyor without success (e.g. https://ci.appveyor.com/project/paulmueller/dclab/builds/36209279/job/4n85sx8i3siua18i).

Related issues:
- #584
- #619
- #624
- #688

After reading other issues, there were apparently fixes for a similar issue (#685 and #686).

**Comment by paulmueller** [comment]
I strongly believe that this is error is related to the PATH or R_HOME variables not set properly. The confusing thing is that some parts of rpy2 correctly guess the variables, but others don't. Being not a native Windows user, I also didn't know that the PATH variable should not contain any ``"`` or double ``\\``. I believe that's what fixed it for me. If you are on appveyor, this is what will save you (https://ci.appveyor.com/project/paulmueller/dclab/builds/36213064/job/s528jgf75luqy6b1):

```yaml
environment:
  PYTHON: "C:\\Python36-x64"
  R_VERSION: 3.6.3

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - choco install -y wget --version 1.20
  - wget -q https://cran.r-project.org/bin/windows/base/old/%R_VERSION%/R-%R_VERSION%-win.exe
  - R-%R_VERSION%-win.exe /SILENT /DIR="C:\\Users\\appveyor\\R"
  - set R_HOME=C:\Users\appveyor\R
  - set PATH=%PATH%;C:\Users\appveyor\R\bin\x64
  - set PATH=%PATH%;C:\Users\appveyor\R\bin\i386
  - set RPY2_CFFI_MODE="ABI"
  - pip install rpy2
  - python -c "from rpy2 import situation; [print(ss) for ss in situation.iter_info()]"
```

The main problem here is that rpy2 is not verbose enough about which directories it knows and which not.

**Comment by OnlyBelter** [comment]
According to [the document](https://rpy2.github.io/doc/latest/html/overview.html#requirements), 

> Running rpy2 on Windows is currently not supported although relative success was recently reported with the lastest in the 3.3.x series.

Could you please support Windows officially! There are more than one package for `R` to use `Python`.

**Comment by lgautier** [comment]
I'll gladly review PRs that improve on the current limited Windows support. Otherwise I do not have the bandwidth work on support Windows myself.

**Comment by ievgennaida** [comment]
Same problem.
We have tried R_HOME and PATH
rpy2 Output folder and file both exists

**Comment by meredithjackson** [comment]
Any Updates on this issue?

**Comment by lgautier** [comment]
Are the answers here helpful?
https://stackoverflow.com/questions/62596681/attempting-to-run-rpy2-in-python-and-receiving-error-0x7e

**Comment by lgautier** [comment]
Binary wheels are now built by the CI pipeline. They install and pass tests.
