### ISSUE TITLE
FactorVector constructor cannot take numeric list or array

### ISSUE THREAD

**Issue by kgoettler** [rpy2/rpy2#728]
**Describe the issue or bug**

Observed in rpy2 3.3.5. FactorVectors cannot be constructed from numeric lists or arrays. Only string lists and arrays appear to work.

**To Reproduce**

```python3
import rpy2.robjects as ro

f = [1, 2, 3, 1, 2, 3]
fr = ro.vectors.FactorVector(f)
```

crashes with the error given below

**Expected behavior**

I would expect `fr` to be a FactorVector with levels 1, 2, and 3.

**Error**

```python3
Traceback (most recent call last):
  File "/home/kgoettler/miniconda3/envs/main/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py", line 598, in from_object
    mv = memoryview(obj)
TypeError: memoryview: a bytes-like object is required, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    fr = ro.vectors.FactorVector(f)
  File "/home/kgoettler/miniconda3/envs/main/lib/python3.8/site-packages/rpy2/robjects/vectors.py", line 533, in __init__
    obj = StrSexpVector(obj)
  File "/home/kgoettler/miniconda3/envs/main/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py", line 512, in __init__
    super().__init__(self.from_object(obj).__sexp__)
  File "/home/kgoettler/miniconda3/envs/main/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py", line 602, in from_object
    res = cls.from_iterable(obj)
  File "/home/kgoettler/miniconda3/envs/main/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 44, in _
    cdata = function(*args, **kwargs)
  File "/home/kgoettler/miniconda3/envs/main/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py", line 541, in from_iterable
    populate_func(iterable, r_vector, set_elt, cast_value)
  File "/home/kgoettler/miniconda3/envs/main/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py", line 463, in _populate_r_vector
    set_elt(r_vector, i, cast_value(v))
  File "/home/kgoettler/miniconda3/envs/main/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py", line 665, in _as_charsxp_cdata
    return conversion._str_to_charsxp(x)
  File "/home/kgoettler/miniconda3/envs/main/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 139, in _str_to_charsxp
    cchar = _str_to_cchar(val)
  File "/home/kgoettler/miniconda3/envs/main/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 118, in _str_to_cchar
    b = s.encode(encoding)
AttributeError: 'int' object has no attribute 'encode'
```

**Additional context**

I'm using rpy2 3.3.5 on Ubuntu 20.04. The last version of rpy2 I used was 2.9.4 and I didn't have this issue. Happy to provide additional context if needed.

**Comment by lgautier** [comment]
Yes, this changed in 3.0.0. The rational was that all levels in an R factor must be strings, with R casting  to strings silently if necessary, and this may create confusion when trying to round-trip with the conversion system. One starting with a sequence of non-str Python object, converting to an R factor, and they back to Python might be surprised to see that the original type is gone and all elements are strings.

When going over this again because of your report I am less convinced that this is a good idea so I wrote a fix.

But now that I wrote this explanation I am not sure that the fix is a good idea and may be I should revert it and let users cast items to string if they chose to.

**Comment by lgautier** [comment]
The error is intended. Whether this is a good decision can obviously be debated but in R vectors turned into factors will see the level converted to strings:

```r
> str(factor(c(1,2,3,1)))
 Factor w/ 3 levels "1","2","3": 1 2 3 1
```

This can be a surprise for a Python user as levels in pandas factor can the objects of any type (although I suspect that objects must be hashable). rpy2 is trying to avoid potentially hard to find issues by requiring arrays of R strings. This comes at the cost of requiring the conversion to string to be explicitly handled by the user on the Python side when the sequence has other elements than strings.
