### ISSUE TITLE
unable to print StrVector with Chinese characters on windows

### ISSUE THREAD

**Issue by shil3754** [rpy2/rpy2#827]
OS: windows 10 professional
Python version: 3.6, 3.8
rpy2 version: 3.4.5

**To Reproduce**
```
from rpy2 import robjects
str1 = robjects.StrVector(['你', '好'])
print(str1)
```
I have no problem with running the code on Linux or Mac, but on windows the following error is reported:

```
From cffi callback <function _consolewrite_ex at 0x000002088CB38488>:
Traceback (most recent call last):
  File "C:\Users\shil3754\AppData\Local\Continuum\anaconda3\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 132, in _consolewrite_ex
    s = conversion._cchar_to_str_with_maxlen(buf, n, _CCHAR_ENCODING)
  File "C:\Users\shil3754\AppData\Local\Continuum\anaconda3\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 133, in _cchar_to_str_with_maxlen
    s = ffi.string(c, maxlen).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2: invalid continuation byte
From cffi callback <function _consolewrite_ex at 0x000002088CB38488>:
Traceback (most recent call last):
  File "C:\Users\shil3754\AppData\Local\Continuum\anaconda3\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 132, in _consolewrite_ex
    s = conversion._cchar_to_str_with_maxlen(buf, n, _CCHAR_ENCODING)
  File "C:\Users\shil3754\AppData\Local\Continuum\anaconda3\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 133, in _cchar_to_str_with_maxlen
    s = ffi.string(c, maxlen).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 2: invalid start byte
```
I have tried several different PCs and the problem persists. It seems that if the rpy2 version is 2.9.2, no error is reported even when the code is run on windows.

**Comment by shil3754** [comment]
> At which of those 2 lines does the code fail? The first one or the second one?
> 
> ```python
> str1 = robjects.StrVector(['你', '好'])
> print(str1)
> ```
> 
> Also, what is the R version?

Just wonder if there is any update on this issue.

**Comment by lgautier** [comment]
It can take time, and often rely on contributions from someone using Windows. 
I don't have a Windows development environment for rpy2. The code snippet in the issue is working without error on Linux.

I suspect that this is down to encoding. rpy2 assumes 'utf-8' strings on the Python side. Is your system using a GB or Big5 encoding?

You could also try the following hack, but there is a good chance that breaks things elsewhere:
```python
rpy2.rinterface_lib.callbacks._CCHAR_ENCODING = '<your encoding>'
```

**Comment by shil3754** [comment]
> It can take time, and often rely on contributions from someone using Windows. I don't have a Windows development environment for rpy2. The code snippet in the issue is working without error on Linux.
> 
> I suspect that this is down to encoding. rpy2 assumes 'utf-8' strings on the Python side. Is your system using a GB or Big5 encoding?
> 
> You could also try the following hack, but there is a good chance that breaks things elsewhere:
> 
> ```python
> rpy2.rinterface_lib.callbacks._CCHAR_ENCODING = '<your encoding>'
> ```

Yes, if I run
`rpy2.rinterface_lib.callbacks._CCHAR_ENCODING = 'GBK'`
first, and then run
```
str1 = robjects.StrVector(['你', '好'])
print(str1)
```
no errors are reported.
