### ISSUE TITLE
rpy2 on Windows error - package 'stats' in options("defaultPackages") was not found

### ISSUE THREAD

**Issue by sreedat** [rpy2/rpy2#848]
**Describe the issue or bug**
After installing python=3.10.2 from conda-forge, then installed R-4.1.2 from CRAN and then installed rpy2=3.4.5 using pip. I launched ```python``` and ran ```import rpy2.robjects as robjects```

results in
```During startup - Warning message:
package 'stats' in options("defaultPackages") was not found
```

**To Reproduce**

Assumes there is an Anaconda or a Miniconda installed:
1. ```conda create -n randpy -c conda-forge python```
2. ```Install R-4.1.2 from CRAN```
3. ```conda activate randpy```
3. ```pip install rpy2```
4. ```python```
5. ```import rpy2.robjects as robjects```

**Expected behavior**
The command ```import ...``` should work without any error

**Error**
```During startup - Warning message:
package 'stats' in options("defaultPackages") was not found
```

**Additional context**
When the command ```python -m rpy2.situation``` the output below shows ```rpy2``` reads the R_HOME variable and location correctly.

Output:
```
rpy2 version:
3.4.5
Python version:
3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:27:13) [MSC v.1929 64 bit (AMD64)]
Looking for R's HOME:
    Environment variable R_HOME: C:\Users\sreedat\Documents\R\R-4.1.2
    InstallPath in the registry: C:\Users\sreedat\Documents\R\R-4.1.2
    Environment variable R_USER: None
    Environment variable R_LIBS_USER: None
R version:
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

    In the PATH:
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['C:/Users/sreedat/Documents/R/R-4.1.2/include', 'C:/Users/sreedat/Documents/R/R-4.1.2/include/x64']
  libraries:
  ['R', 'm']
  library_dirs:
  ['C:/Users/sreedat/Documents/R/R-4.1.2/bin/x64']
  extra_compile_args:
  []
  extra_link_args:
  []
```

**Comment by sreedat** [comment]
I was able to resolve this error by changing the versions of ```python``` and channel(s) I used to install ```rpy2```. As much as possible I installed all the packages / libraries from conda-forge and this error went away. I'm testing some more and once it is stable I will post the instructions and configurations here

**Comment by lgautier** [comment]
Thanks. `conda` has been at the root of many issues. It could be a bug or feature of `conda`, but the general resolution was to avoid mixing conda packages and pip installation. Note that rpy2 does not support Windows well. Consider using the Windows Subsystem for Linux when on Windows.

**Comment by spadavec** [comment]
I'm getting the same error, and I can't even run the following: 

```
python -m rpy2.situation
rpy2 version:
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/p36_bk/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/miniconda3/envs/p36_bk/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/miniconda3/envs/p36_bk/lib/python3.6/site-packages/rpy2/situation.py", line 140, in <module>
    for row in iter_info():
  File "/home/user/miniconda3/envs/p36_bk/lib/python3.6/site-packages/rpy2/situation.py", line 102, in iter_info
    yield rpy2.__version__
UnboundLocalError: local variable 'rpy2' referenced before assignment
```

I'm on linux 18.04

**Comment by ThyssenQi** [comment]
I referred to it to solve similar problems, you can give it a try.
https://github.com/rpy2/rpy2/issues/771

**Comment by lgautier** [comment]
The CI pipeline is building and tests binary wheels for Windows. This is presumably resolved.

**Comment by halt9k** [comment]
@ulyssegatard this happens only with recent versions of R (seems does not happen on 4.5.0) if `R.dll` is not in the PATH. Previously, `R.dll` and `R.exe` were in the same folder, now there is some sort of duplicate.
Usually, it will be somewhere under `C:\Program Files\R\R-4.6.1\bin\x64`.
After adding, verify `where R.dll` resolves correctly from `cmd`.

This was reopened as https://github.com/rpy2/rpy2/issues/1243.
