### ISSUE TITLE
StrVector: arrays of python objects that support str() aren't automatically converted to str

### ISSUE THREAD

**Issue by tboddyspargo** [rpy2/rpy2#851]
**Describe the issue or bug**
It's my understanding that `StrVector` class is expected to automatically convert objects that support `str()` to `str`. However, in my case, this is not happening when I pass it a list of `datetime` objects. Instead, `_str_to_cchar()` is raising an exception because it got an unexpected `datetime` object.

Am I misunderstanding which types of objects will be automatically cast to `str` before being sent to `_as_charsxp_cdata()`?

**To Reproduce**
In a python 3.9.10 interpreter with `datetime` and `rpy==3.3.6` installed, run the following:

```python
import rpy2.robjects as ro
from datetime import datetime
arr = [datetime.now(), datetime.now()]
ro.StrVector(arr)
```

**Expected behavior**
I expected `datetime` objects to automatically be converted to `str` such that the `_str_to_cchar()` function will work.

**Error**
```log
Traceback (most recent call last):
  File "/Users/tyler/.pyenv/versions/3.9.10/lib/python3.9/site-packages/rpy2/rinterface_lib/sexp.py", line 599, in from_object
    mv = memoryview(obj)
TypeError: memoryview: a bytes-like object is required, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tyler/.pyenv/versions/3.9.10/lib/python3.9/site-packages/rpy2/robjects/vectors.py", line 385, in __init__
    super().__init__(obj)
  File "/Users/tyler/.pyenv/versions/3.9.10/lib/python3.9/site-packages/rpy2/rinterface_lib/sexp.py", line 512, in __init__
    super().__init__(self.from_object(obj).__sexp__)
  File "/Users/tyler/.pyenv/versions/3.9.10/lib/python3.9/site-packages/rpy2/rinterface_lib/sexp.py", line 603, in from_object
    res = cls.from_iterable(obj)
  File "/Users/tyler/.pyenv/versions/3.9.10/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py", line 44, in _
    cdata = function(*args, **kwargs)
  File "/Users/tyler/.pyenv/versions/3.9.10/lib/python3.9/site-packages/rpy2/rinterface_lib/sexp.py", line 541, in from_iterable
    populate_func(iterable, r_vector, set_elt, cast_value)
  File "/Users/tyler/.pyenv/versions/3.9.10/lib/python3.9/site-packages/rpy2/rinterface_lib/sexp.py", line 463, in _populate_r_vector
    set_elt(r_vector, i, cast_value(v))
  File "/Users/tyler/.pyenv/versions/3.9.10/lib/python3.9/site-packages/rpy2/rinterface_lib/sexp.py", line 666, in _as_charsxp_cdata
    return conversion._str_to_charsxp(x)
  File "/Users/tyler/.pyenv/versions/3.9.10/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py", line 139, in _str_to_charsxp
    cchar = _str_to_cchar(val)
  File "/Users/tyler/.pyenv/versions/3.9.10/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py", line 118, in _str_to_cchar
    b = s.encode(encoding)
AttributeError: 'datetime.datetime' object has no attribute 'encode'
```

**Comment by tboddyspargo** [comment]
This might be naive, but is the issue simply that  the following change is necessary?
https://github.com/rpy2/rpy2/blob/98bc17e519e89c5dcb01900fd9a1d8b0e98f8913/rpy2/rinterface_lib/sexp.py#L723

```diff
        elif isinstance(i, slice):
            for i_c, v in zip(range(*i.indices(len(self))), value):
                if v is None:
                    v_cdata = openrlib.rlib.R_NaString
                else:
-                    if not isinstance(value, str):
+                    if not isinstance(v, str):
                        v = str(v)
                    v_cdata = _as_charsxp_cdata(v)
```

**Comment by tboddyspargo** [comment]
For others that might come across this issue, my work-around is to call `str()` myself on each item in the list before passing it to `StrVector`

**Comment by lgautier** [comment]
Like for issue #794 , this is coming from the choice of failing rather than  

> This might be naive, but is the issue simply that the following change is necessary?
> 
> https://github.com/rpy2/rpy2/blob/98bc17e519e89c5dcb01900fd9a1d8b0e98f8913/rpy2/rinterface_lib/sexp.py#L723
> 
> ```diff
>         elif isinstance(i, slice):
>             for i_c, v in zip(range(*i.indices(len(self))), value):
>                 if v is None:
>                     v_cdata = openrlib.rlib.R_NaString
>                 else:
> -                    if not isinstance(value, str):
> +                    if not isinstance(v, str):
>                         v = str(v)
>                     v_cdata = _as_charsxp_cdata(v)
> ```

It looks like a bug in code indeed.

**Comment by lgautier** [comment]
This was fixed in the dev branch while ensuring that the code passed type checks with `mypy`. The upcoming release 3.5.0 will include that fix.

I will probably not have the bandwidth to have this in a bugfix release for the 3.4.x series.

**Comment by tboddyspargo** [comment]
@lgautier - Thank you very much for your time!
