### ISSUE TITLE
"R_Home is none" Error? Issue with rpy2.objects

### ISSUE THREAD

**Issue by gabrielpulga** [rpy2/rpy2#865]
**Describe the issue or bug**

I'm getting a value error when running a basic python script with rpy2.

**To Reproduce**

When running the following python code with `python3 script.py`, it seems like there's something wrong with the installation, due to the nature of the error I would guess it has something to do with version incompatibility or other with either python or rpy2.

_script.py_
```
import rpy2.robjects as robjects

pi = robjects.r['pi'] 
```

**Expected behavior**

It should output the value of Pi - like in the doc. https://rpy.sourceforge.io/rpy2/doc-dev/html/introduction.html#getting-started

**Error**

Here's the traceback on what happens.

```
Traceback (most recent call last):
  File "/home/gabriel/Projects/cap-markets-r-workflows/Turning R into Python/script.py", line 1, in <module>
    import rpy2.robjects as robjects
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.7_1/lib/python3.9/site-packages/rpy2/robjects/__init__.py", line 14, in <module>
    import rpy2.rinterface as rinterface
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.7_1/lib/python3.9/site-packages/rpy2/rinterface.py", line 6, in <module>
    from rpy2.rinterface_lib import openrlib
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.7_1/lib/python3.9/site-packages/rpy2/rinterface_lib/openrlib.py", line 23, in <module>
    rlib = _dlopen_rlib(R_HOME)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.7_1/lib/python3.9/site-packages/rpy2/rinterface_lib/openrlib.py", line 16, in _dlopen_rlib
    raise ValueError('r_home is None. '
ValueError: r_home is None. Try python -m rpy2.situation
```

**Comment by gabrielpulga** [comment]
Also, I forgot to mention - here's the traceback for trying to build rpy2.situation specifically, which is what the output recommends :

```
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.7_1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.7_1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.7_1/lib/python3.9/site-packages/rpy2/situation.py", line 140, in <module>
    for row in iter_info():
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.7_1/lib/python3.9/site-packages/rpy2/situation.py", line 102, in iter_info
    yield rpy2.__version__
UnboundLocalError: local variable 'rpy2' referenced before assignment
```

**Comment by lgautier** [comment]
The traceback does not seem to correspond to the latest release. Which version of rpy2 are you using?

You can get the version with:

```bash
python -c 'import rpy2; print(rpy2.__version__)'
```
