### ISSUE TITLE
problem running R scripts with accented characters (wrong output)

### ISSUE THREAD

**Issue by abubelinha** [rpy2/rpy2#868]
**Describe the issue or bug**

When I try to run a R script which contains utf8 characters with accents, tildes, then I got an error instead of viewing the correct characters (which I can view normally in R console).
Not sure if this has some relation with [#551](https://github.com/rpy2/rpy2/issues/551#issuecomment-560199993) or not. But I tried the proposed solution and it didn't work.

**To Reproduce**
```Python
#!/usr/bin/python
# -*- coding: utf-8 -*-
import rpy2.robjects as robjects
if True: # taken from issue #551 , but either with True/False, I got the same error
	# https://github.com/rpy2/rpy2/issues/551#issuecomment-560199993
	import rpy2.rinterface_lib.conversion
	rpy2.rinterface_lib.conversion._CE_UTF8 = 1
Rscript = '''
	print("Begin of R script output")
	print("áèîõüçñ")
	print("End of R script output")
'''
print(rpy2.__version__)
# I output the script content, just to show that my Python console can output these characters correctly:
print("This is my Rscript:\n------------\n", Rscript, "\n---------------")
result = robjects.r(Rscript)
```
My script above is saved as a .py UTF-8 file without BOM.

**Expected behavior**
This is the output when I run `Rscript` content from my RGui (64-bit) R console (R version 3.6.3):
```
> print("Begin of R script output")
[1] "Begin of R script output"
> print("áèîõüçñ")
[1] "áèîõüçñ"
> print("End of R script output")
[1] "End of R script output"
```
My RGui Windows program saves its scripts as ANSI files (but I don't think it matters here at all: as I said above, my .py script is saved as UTF-8 without BOM).

**Error**

```
3.4.5
This is my Rscript:
	print("Begin of R script output")
	print("áèîõüçñ")
	print("End of R script output")
[1] "Begin of R script output"
[1]From cffi callback <function _consolewrite_ex at 0x0000000003663430>:
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 132, in _consolewrite_ex
    s = conversion._cchar_to_str_with_maxlen(buf, n, _CCHAR_ENCODING)
  File "C:\Python38\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 133, in _cchar_to_str_with_maxlen
    s = ffi.string(c, maxlen).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 2: invalid continuation byte

[1] "End of R script output"
```

**Additional context**
Windows XP 64bit
Python 3.8
rpy2 3.4.5, 

I also tried @lgautier script in [#754](https://github.com/rpy2/rpy2/issues/754#issuecomment-748540620). Unfortunately I don't have skills for understanding most of that discussion, but anyway this is my output, just in case it's helpful for my issue:
```
x: CETYPE.CE_LATIN1
y: CETYPE.CE_NATIVE
z: CETYPE.CE_LATIN1, CETYPE.CE_NATIVE, CETYPE.CE_NATIVE
```

**Comment by lgautier** [comment]
There is no error with Linux. This seems Windows-specific.

**Comment by zhibisora** [comment]
As #754 says, r uses windows-1252(CP-1252) encoding for standard output on windows, and although #754 has been closed, it seems that rpy2 still uses utf-8 to read standard output, which causes errors with special characters.

**Comment by zhibisora** [comment]
You can try this
```python
import rpy2
import rpy2.robjects as robjects

if __name__ == '__main__':
    text = "áèîõüçñ".encode('unicode_escape').decode()
    print(text)  # \xe1\xe8\xee\xf5\xfc\xe7\xf1 in python

    text2 = "áèîõüçñ"
    print(text2)  # áèîõüçñ in python

    Rscript = '''
    library('readr')
    
    print("Begin of R script output")
    
    text <- ''' + f"'{text}'" + '''
    write_file(text, "txt-r.txt", append = FALSE)
    print("text is output to txt-r.txt")
    
    text2 <- ''' + f"'{text2}'" + '''
    write_file(text2, "txt-r2.txt", append = FALSE)
    print("text2 is output to txt2-r.txt")
    
    print("End of R script output")
    '''
    print(rpy2.__version__)
    # I output the script content, just to show that my Python console can output these characters correctly:
    print("This is my Rscript:\n------------\n", Rscript, "\n---------------")
    result = robjects.r(Rscript)

```
And then you can see this in txt-r.txt:
```txt
# txt-r.txt
áèîõüçñ  
```
in txt2-r.txt
```txt
# txt2-r.txt
¨¢¨¨<U+00EE><U+00F5>¨¹<U+00E7><U+00F1>
```

This shows that using the special cross-platform output r package can skip the problem of having to use cp1252 output due to the c library on win. 

But internally, python strings (with special characters) must be encoded in unicode before they can be passed to r, so that r will use utf-8 to parse the strings, otherwise, as in txt2, r uses cp1252 to receive the strings, which results the value of 'text2' in the r environment being simply wrong and not available for data processing, while the value of 'text' is correct. 

But even so this only bypasses the standard output problem, if you use standard output like 'print(text)', this will still report an error because the standard output will convert it to cp1252, which works in the console (but may have display errors), but it seems that rpy2 does not support it. If you use RGui or Rstudio to output successfully, it is because the console of these tools comes with utf-8 output, not the standard output of r itself.

These only appear on windows, because on linux and macos r also uses utf-8 internally for parsing and output, so there are no character errors in either python to r string passing or printing using standard output.

**Comment by abubelinha** [comment]
A bit complicated for my understanding, but thanks a lot for your answer.

I guess I must stick to Linux in order to use rpy2.

**Comment by zhibisora** [comment]
> A bit complicated for my understanding, but thanks a lot for your answer.
> 
> I guess for now I must stick to Linux in order to use rpy2.

If you can, this is the best solution. Because as far as I know rpy2 has a lot of work to do to provide full support on windows.

**Comment by zhibisora** [comment]
After some research I learned that after r4.2.0 r uses utf-8 as the internal encoding. But even with r4.2.0, I still get encoding errors, which means that there is a problem with the encoding of the output from r in the rpy2 c library on windows.

The good news is that in r4.2.0 the part of https://github.com/rpy2/rpy2/issues/868#issuecomment-1227008951 that gets the python output from r is no longer a problem, there is no need to convert the r script to unicode in python in advance.

But in r4.2.0, I also got some other problems that didn't happen before r4.2.0, which led me to speculate that the rpy2 c library encodes the output of r on windows using system native encoding, and decodes it using utf-8.

This makes the following solution valid:
```python
# Change the internal variables in callbacks.py in rpy2,
# note that this changes your local package, 
# please only use it for personal use or testing
_CCHAR_ENCODING = 'cp1252'  # Your system native encoding
```
![image](https://user-images.githubusercontent.com/73344387/187032520-10bdb3ca-c5ea-456b-bc1c-55b4c5a22134.png)
