### ISSUE TITLE
`RS4Auto_Type` class instantiation: "TypeError: LMERMod() takes no arguments"

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [rpy2/rpy2#883]
**Describe the issue or bug**

I'm trying to put together the info from 2 sections of the documentation---[Working with R's OOPs - Automated R in Python class definition](https://rpy2.github.io/doc/latest/html/robjects_oop.html#automated-r-in-python-class-definitions) and [Mapping rpy2 objects to arbitrary python objects - Customizing the conversion](https://rpy2.github.io/doc/latest/html/robjects_convert.html#customizing-the-conversion)---but without a success. Specifically, I'm trying to make `lmerMod` R class to be mapped in Python. 

**To Reproduce**

```python
import rpy2.robjects as ro
import rpy2.rinterface as ri
from rpy2.robjects.packages import importr
from rpy2.robjects.methods import RS4Auto_Type
from rpy2.robjects.conversion import localconverter
from rpy2.robjects import pandas2ri

# dummy data
import pandas as pd
import numpy as np
sleepstudy = pd.DataFrame(data='Subject':np.random.randint(1,12,100),'Days':np.random.randint(1,10,100),'Reaction':np.random.rand(100)})

lme4 = importr('lme4')

class LMER(metaclass=RS4Auto_Type):
  __rname__ = 'lmerMod'
  __rpackagename__ = 'lme4'

# If this empty class from the documentation is used instead, the code runs successfully
#class LMER(robjects.RS4):
#    """Custom class."""
#    pass

# Map the R/S4 class 'lmerMod' to our Python class LMER.
with (localconverter(ro.default_converter + pandas2ri.converter),  
      ro.conversion.converter.rclass_map_context(ri.SexpS4,{'lmerMod': LMER})):
    res2 = lme4.lmer(formula = ro.Formula('Reaction ~ Days + (Days | Subject)'), data=sleepstudy)
```

**Expected behavior**
`res2` to be an `LMER` object with all R attributes & methods made available.

**Error**

```
Traceback (most recent call last):
  File "C:\Users\show_rpy2_bug.py", line 44, in <module>
    res2 = lme4.lmer(formula = ro.Formula('Reaction ~ Days + (Days | Subject)'), data=sleepstudy)
  File "C:\Users\.venv\lib\site-packages\rpy2\robjects\functions.py", line 202, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "C:\Users\.venv\lib\site-packages\rpy2\robjects\functions.py", line 126, in __call__
    res = cv.rpy2py(res)
  File "C:\Users\Python\Python39\lib\functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\.venv\lib\site-packages\rpy2\robjects\__init__.py", line 245, in _rpy2py_sexps4
    return cls(obj)
TypeError: LMER() takes no arguments
```

**Additional context**

Results are produced with Python v3.9.9, R v4.2.0, and rpy2 v3.5.2 in Windows 10. (I do realize the rpy2 is not supported under Windows 10, but the error seems to be non-OS related.)

**Comment by lgautier** [comment]
Some of the doc is not under CI/CD unfortunately.

I see that this is not under unit-tests either:
https://github.com/rpy2/rpy2/blob/master/rpy2/tests/robjects/test_methods.py#L98

**Comment by tikuma-lsuhsc** [comment]
Yeah, I've noticed much of `RS4Auto_Type` is still in a rough shape with minimal testing as I've been dove deeper into the `rpy2` codebase a bit more since I posted this issue. I really like the concept though and willing to help if interested.

Anyway, I have figured out how to make the above code to run: it needs `RS4` as the base class in addition to the metaclass.

```python
class LMER(RS4, metaclass=RS4Auto_Type):
  __rname__ = 'lmerMod'
  __rpackagename__ = 'lme4'
```

This class successfully instantiates *but* it didn't do a good job of picking up the methods and slots:

```python
dir(res2)
```

yields

```python
<class '__main__.LMER'>
['_RObjectMixin__close', '_RObjectMixin__fifo', '_RObjectMixin__file', '_RObjectMixin__readlines', '_RObjectMixin__show', 
'_RObjectMixin__sink', '_RObjectMixin__slots', '_RObjectMixin__tempfile', '_RObjectMixin__unlink', '__abstractmethods__', 
'__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', 
'__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', 
'__reduce_ex__', '__repr__', '__rname__', '__rpackagename__', '__setattr__', '__setstate__', '__sexp__', '__sexp_refcount__', '__sizeof__', 
'__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_sexpobject', 'call', 'data.frame', 'do_slot', 'do_slot_assign', 
'extends', 'get_attrib', 'integer', 'isclass', 'list', 'list_attrs', 'lmerResp', 'merPredD', 'named', 'names', 'names_from_c_attribute', 
'numeric', 'r_repr', 'rclass', 'rid', 'rsame', 'slotnames', 'slots', 'typeof', 'validobject']
```

Only `lmer` related attributes are `lmerResp`, and `merPredD` (I think).

After studying `RSAuto_typ` code, I ended up writing my own semi-auto base class and built `LMER` class based on it. (Doing this while learning the basics of R was quite intense but very valuable experience!)

**Comment by lgautier** [comment]
> Yeah, I've noticed much of `RS4Auto_Type` is still in a rough shape with minimal testing as I've been dove deeper into the `rpy2` codebase since I posted this issue. I really like the concept though and willing to help if interested.

rpy2 works in limited ways on Windows. I suggest that you use Window Subsystem for Linux. I heard that it works well that way.

Otherwise I am happy to discuss how things could be done better / review a PR. The absence of unit tests makes me wonder how much of that code is still working after code updates.

Also, I have experimented further with the dynamic generation of Python classes from R class definitions in rpy2-R6: https://github.com/rpy2/rpy2-R6 .

> Anyway, I have figured out how to make the above code to run: it needs `RS4` as the base class in addition to the metaclass.
> 
> ```python
> class LMER(RS4, metaclass=RS4Auto_Type):
>   __rname__ = 'lmerMod'
>   __rpackagename__ = 'lme4'
> ```

Yes, that's one way to make it work.

> This class successfully instantiates _but_ it didn't do a good job of picking up the methods and slots:
> 
> ```python
> dir(res2)
> ```
> 
> yields
> 
> ```python
> <class '__main__.LMER'>
> ['_RObjectMixin__close', '_RObjectMixin__fifo', '_RObjectMixin__file', '_RObjectMixin__readlines', '_RObjectMixin__show', 
> '_RObjectMixin__sink', '_RObjectMixin__slots', '_RObjectMixin__tempfile', '_RObjectMixin__unlink', '__abstractmethods__', 
> '__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', 
> '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', 
> '__reduce_ex__', '__repr__', '__rname__', '__rpackagename__', '__setattr__', '__setstate__', '__sexp__', '__sexp_refcount__', '__sizeof__', 
> '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_sexpobject', 'call', 'data.frame', 'do_slot', 'do_slot_assign', 
> 'extends', 'get_attrib', 'integer', 'isclass', 'list', 'list_attrs', 'lmerResp', 'merPredD', 'named', 'names', 'names_from_c_attribute', 
> 'numeric', 'r_repr', 'rclass', 'rid', 'rsame', 'slotnames', 'slots', 'typeof', 'validobject']
> ```
> 
> Only `lmer` related attributes are `lmerResp`, and `merPredD` (I think).

The other attributes and methods come from `RS4`, the parent class for `LMER` you have chosen.

> After studying `RSAuto_typ` code, I ended up writing my own semi-auto base class and built `LMER` class based on it. (Doing this while learning the basics of R was quite intense but very valuable experience!)

An alternative is to define `LMER` with a parent class that comes with less attributes and methods, and if it does not have a suitable `__init__()` method write one.

For example, the following will work and return an instance with less bells and whistles as the parent class is from rpy2's "low level" interface:

```python
import rpy2.rinterface
class LMER(rpy2.rinterface.SexpS4, metaclass=RS4Auto_Type):
    __rname__ = 'lmerMod'
    __rpackagename__ = 'lme4'
```

You could go further and a have a minimal `rpy2.rinterface_lib._rinterface_capi.SupportsSEXP`-compatible class (check this to have an idea about what `__init__` would have to be like: 
https://github.com/rpy2/rpy2/blob/79ff017c8c10476eb71cc84bd158d011dcfe1440/rpy2/rinterface_lib/sexp.py#L87), or even have a Python namespace without `SupportSEXP` compatibility (although this will likely require a "py2rpy" rule if you want to be able to pass the object back to R).

**Comment by tikuma-lsuhsc** [comment]
> rpy2 works in limited ways on Windows

It has been rock solid for me except for the `R_HOME` issue from the other thread/PR.

> Otherwise I am happy to discuss how things could be done better / review a PR. The absence of unit tests makes me wonder how much of that code is still working after code updates.

Cool. I'll take a stab at it in a coming weeks with the additional info you spelled it out above (much appreciate it, btw!) It would be a good opportunity for me to learn about Python meta-class.  Anyway, a tricky part of offering an auto-wrapper IMO is how to offer (or not to offer) an interface to a local converter (of user's choice). Specifically, I'm wondering allowing metaclass argument (a la [the mechanism in this post](https://stackoverflow.com/questions/13762231) so R methods are made available in a raw form with `_name()` and converter wrapped version with `name()`. If this makes sense to you.

**Comment by lgautier** [comment]
> > rpy2 works in limited ways on Windows
> 
> It has been rock solid for me except for the `R_HOME` issue from the other thread/PR.
> 
> > Otherwise I am happy to discuss how things could be done better / review a PR. The absence of unit tests makes me wonder how much of that code is still working after code updates.
> 
> Cool. I'll take a stab at it in a coming weeks with the additional info you spelled it out above (much appreciate it, btw!) It would be a good opportunity for me to learn about Python meta-class. Anyway, a tricky part of offering an auto-wrapper IMO is how to offer (or not to offer) an interface to a local converter (of user's choice). Specifically, I'm wondering allowing metaclass argument (a la [the mechanism in this post](https://stackoverflow.com/questions/13762231) so R methods are made available in a raw form with `_name()` and converter wrapped version with `name()`. If this makes sense to you.

I think I understand, and it makes sense. However, name clashes (attribute names overriding methods and attributes important for the class) is what concerned me since they can be anything. What I thought about was to have a top level attribute (let's call it `name` to be close to your proposed naming scheme) that is merely a namespace. This would allow having dynamically-generated attributes without fear of name clashes. I think that this is the approach taken by `spacy`  (https://spacy.io/usage/processing-pipelines#custom-components-attributes).
