### ISSUE TITLE
from rpy2.robjects import pandas2ri error

### ISSUE THREAD

**Issue by john120120** [rpy2/rpy2#932]
I am a newbie in this single cell analysis area and have a hard time fixing this problem 

from rpy2.robjects import pandas2ri
R[write to console]: Error in gettext(fmt, domain = domain, trim = trim) : 
  3 arguments passed to .Internal(gettext) which requires 2

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leesuho/miniconda3/envs/single_cell/lib/python3.10/site-packages/rpy2/robjects/__init__.py", line 18, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/Users/leesuho/miniconda3/envs/single_cell/lib/python3.10/site-packages/rpy2/robjects/robject.py", line 86, in <module>
    class RObjectMixin(abc.ABC):
  File "/Users/leesuho/miniconda3/envs/single_cell/lib/python3.10/site-packages/rpy2/robjects/robject.py", line 98, in RObjectMixin
    __show = _get_exported_value('methods', 'show')
  File "/Users/leesuho/miniconda3/envs/single_cell/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/Users/leesuho/miniconda3/envs/single_cell/lib/python3.10/site-packages/rpy2/rinterface.py", line 810, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in gettext(fmt, domain = domain, trim = trim) : 
  3 arguments passed to .Internal(gettext) which requires 2

**Comment by lgautier** [comment]
This seems like either an older version of R is being used, or a conda / environment issue where a mismatching version the R library is found when dynamically loading `libR`.
