### ISSUE TITLE
Docker linux. rpy2: 3.5.7 fails with exception: Conversion rules for `rpy2.robjects` appear to be missing when local convertors are specified.

### ISSUE THREAD

**Issue by ievgennaida** [rpy2/rpy2#978]
**Describe the issue or bug**

Code fails to be executed in another thread even when local convertors are specified.

**rpy2: 3.5.7 FAILS** 

Fails with both code examples
```
    def convert_pandas_to_rdf(self, r_df):
        """convert pandas dataframe to r dataframe"""
        with localconverter(ro.default_converter + pandas2ri.converter):
            return ro.conversion.get_conversion().rpy2py(r_df)
```

```
    with ro.default_converter + pandas2ri.converter:
          return ro.conversion.get_conversion().rpy2py(r_df)


```

**Expected behavior**
Local converters should be used

**Error**

```
 **Conversion rules for `rpy2.robjects` appear to be missing. Those
    rules are in a Python contextvars.ContextVar. This could be caused
    by multithreading code not passing context to the thread.**

```

**Additional context**
```
rpy2 version:
3.5.7
Python version:
3.8.6 (default, Dec 11 2020, 14:38:29)
[GCC 8.3.0]
Looking for R's HOME:
    Environment variable R_HOME: None
    Calling `R RHOME`: /usr/lib/R
    Environment variable R_LIBS_USER: None
R's additions to LD_LIBRARY_PATH:
/usr/lib/R/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
R version:
    In the PATH: R version 4.1.2 (2021-11-01) -- "Bird Hippie"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/usr/share/R/include']
  libraries:
  ['R', 'pcre2-8', 'lzma', 'bz2', 'z', 'rt', 'dl', 'm', 'icuuc', 'icui18n']
  library_dirs:
  ['/usr/lib/R/lib']
  extra_compile_args:
  ['-std=c99']
  extra_link_args:
  ['-Wl,--export-dynamic', '-fopenmp', '-Wl,-z,relro']
Directory for the R shared library:
lib
```

Would appreciate any advice. 
Potentially related issue:
https://github.com/rpy2/rpy2/issues/977

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

**Comment by mdancho84** [comment]
Not that this is a good answer, but I downgraded to `pip install rpy2==3.5.1` and it got me through this issue.

**Comment by ievgennaida** [comment]
Somehow cannot be reproduced using the synthetic example, but bug constantly reproduced for my production environment...

What I have tried:

```
import threading
import asyncio
from concurrent.futures import ThreadPoolExecutor, as_completed
import pandas as pd
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter


def run_in_new_thread():
	print('Thread Started')
	pd_df = pd.DataFrame({'int_values': [1,2,3, 4], 'str_values': ['abc', 'def', 'ghi', None]})
	print('Input dataframe:')			  
	with localconverter(ro.default_converter + pandas2ri.converter):
		converted = ro.conversion.get_conversion().rpy2py(pd_df)
		print('Converted dataframe:')
		print(converted)
		
event_loop = asyncio.get_event_loop()
 
with ThreadPoolExecutor() as exec:
	event_loop.run_in_executor(exec, run_in_new_thread)
		
print('Exiting')
```

**Comment by ievgennaida** [comment]
### Reproduced on linux

Next steps are followed:

- Install Docker on windows to run linux R base. (Docker is **not** using WSL2)
- Run command to create and start using R container
`docker run r-base:4.2.2 -it bash`
-Install python by running the next commands
```
apt install curl build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
wget https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz
tar -xf Python-3.10.*.tgz
cd Python-3.10.*/
./configure --enable-optimizations
make -j 4
make altinstall
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3.10 get-pip.py
Install required python packages
pip install wheel
pip install rpy2==3.5.8
pip install pandas
pip install numpy
Create python file with the content. Ex: using nano
apt install nano 
```
- Run nano and paste next content:
```

import threading
import asyncio
from concurrent.futures import ThreadPoolExecutor, as_completed
import pandas as pd
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter


def convert_r_to_pands():
	print('R->P-> Thread Started -> convert_r_to_pands')
	r_df = ro.DataFrame({"str_column": ro.StrVector( ['abc', 'def'])})
	with localconverter(ro.default_converter + pandas2ri.converter):
		converted = ro.conversion.py2rpy(r_df)
		print('R->P-> Converted dataframe:')
		print(converted)

# Runs Fine:
convert_r_to_pands()
	
# Fails:
thread = threading.Thread(target=convert_r_to_pands)
# run the thread
thread.start()
thread.join()

print('Exiting')
```

- Save with the name test-thread-r.py

- Run command to start script
`python3.10 test-thread-r.py`

- See exception:

```
R->P-> Thread Started -> convert_r_to_pands
R->P-> Converted dataframe:
  str_column
1        abc
2        def

R->P-> Thread Started -> convert_r_to_pands
Exception in thread Thread-1 (convert_r_to_pands):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Python-3.10.0/test3.py", line 13, in convert_r_to_pands
    r_df = ro.DataFrame({"str_column": ro.StrVector( ['abc', 'def'])})
  File "/usr/local/lib/python3.10/site-packages/rpy2/robjects/vectors.py", line 1292, in __init__
    kv = [(str(k), cv.py2rpy(v)) for k, v in obj.items()]
  File "/usr/local/lib/python3.10/site-packages/rpy2/robjects/vectors.py", line 1292, in <listcomp>
    kv = [(str(k), cv.py2rpy(v)) for k, v in obj.items()]
  File "/usr/local/lib/python3.10/functools.py", line 878, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.10/site-packages/rpy2/robjects/conversion.py", line 370, in _raise_missingconverter
    raise NotImplementedError(_missingconverter_msg)
NotImplementedError:
    Conversion rules for `rpy2.robjects` appear to be missing. Those
    rules are in a Python contextvars.ContextVar. This could be caused
    by multithreading code not passing context to the thread.

Exiting
```

**Note Package 3.5.1. works fine**

**Comment by ievgennaida** [comment]
@lgautier Added reproduce steps for both Linux and Windows.
For the temporary solution, I am using 3.5.1 where convertors are wrapped inside of the thread lock due to other concurrency issues.

**Comment by lgautier** [comment]
My understanding is that using Python's `threading` module implies a loss of context as used by `contextvars`. This is up to a user / developer to take care of this. This affects `rpy2` users wanting use `threading` because conversion rules are stored in a context to allow a safe(r) use of context managers for local conversion rules. 

When using the `robjects` high-level interface conversion rules might be present in a lot of places. Ensure that the conversions rules include all interfacing with R. The following slight modification of your example fixes the issue:
 
```python
import threading
import asyncio
from concurrent.futures import ThreadPoolExecutor, as_completed
import pandas as pd
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter


def convert_r_to_pandas():
    print('R->P-> Thread Started -> convert_r_to_pands')
    with localconverter(ro.default_converter + pandas2ri.converter) as cv:
        r_df = ro.DataFrame({"str_column": ro.StrVector( ['abc', 'def'])})
        print(cv)
        converted = cv.rpy2py(r_df)
        print('R->P-> Converted dataframe:')
        print(converted)

# Runs Fine:
convert_r_to_pandas()
	
# Fails:
thread = threading.Thread(target=convert_r_to_pandas)
# run the thread
thread.start()
thread.join()

print('Exiting')
```

**Comment by ievgennaida** [comment]
@lgautier Sounds good, I think iit would be nice to update a doc, it's sounds like a good practice to use convertor explicitly if one is defined using "with" keyword

**Comment by lgautier** [comment]
Added doc.

**Comment by ievgennaida** [comment]
@lgautier when using  with localconverter than I don't need to call 'context'?
` with localconverter(ro.default_converter + pandas2ri.converter) as cv:`
not something like 
` with (ro.default_converter + pandas2ri.converter).context() as cv:`

Thank you

**Comment by lgautier** [comment]
> [@lgautier](https://github.com/lgautier) when using  with localconverter than I don't need to call 'context'? ` with localconverter(ro.default_converter + pandas2ri.converter) as cv:` not something like ` with (ro.default_converter + pandas2ri.converter).context() as cv:`
> 
> Thank you

`localconverter()` still works. The method `context` does the same thing.
