### ISSUE TITLE
importing ggplot2 gives: LookupError: 'print.ggplot' not found 

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#99]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/89) by Anonymous.**

----------------------------------------

on python2.7 and rpy2-2.2.5 attempt to import ggplot2:

**import rpy2.robjects.lib.ggplot2**

gives this error -> **LookupError: 'print.ggplot' not found**

whole error mesagge:
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import rpy2.robjects.lib.ggplot2
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rpy2-2.2.5dev_20120304-py2.7-macosx-10.6-intel.egg/rpy2/robjects/lib/ggplot2.py", line 23, in <module>
    class GGPlot(robjects.RObject):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rpy2-2.2.5dev_20120304-py2.7-macosx-10.6-intel.egg/rpy2/robjects/lib/ggplot2.py", line 26, in GGPlot
    _rprint = ggplot2_env['print.ggplot']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rpy2-2.2.5dev_20120304-py2.7-macosx-10.6-intel.egg/rpy2/robjects/environments.py", line 14, in __getitem__
    res = super(Environment, self).__getitem__(item)
LookupError: 'print.ggplot' not found

**Comment by lgautier** [comment]
Import is working now.
