### ISSUE TITLE
rpy2.robjects error: object 'pkginfo' not found

### ISSUE THREAD

**Issue by EVanderSchel** [rpy2/rpy2#992]
Recently began getting an error when trying to import rpy2.robjects:

R[write to console]: Error in loadNamespace(x) : object 'pkgInfo' not found

It was working in the past but recently I added R_LIBS_USER environment variable to try and resolve an issue with an unrelated R script. When I came back to my python script I started getting this error. I reverted everything back and reinstalled the rpy2 package but am still getting the error.

`import rpy2.robjects as ro`

Traceback (most recent call last):
File "C:\Users\user\AppData\Local\Temp\2\ipykernel_9068\2312183589.py", line 1, in import rpy2.robjects as ro

File "C:\Users\user\AppData\Local\conda\conda\envs\myenv\lib\site-packages\rpy2\robjects_init_.py", line 18, in from rpy2.robjects.robject import RObjectMixin, RObject

File "C:\Users\user\AppData\Local\conda\conda\envs\myenv\lib\site-packages\rpy2\robjects\robject.py", line 81, in class RObjectMixin(abc.ABC):

File "C:\Users\user\AppData\Local\conda\conda\envs\myenv\lib\site-packages\rpy2\robjects\robject.py", line 93, in RObjectMixin __show = _get_exported_value('methods', 'show')

File "C:\Users\user\AppData\Local\conda\conda\envs\myenv\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 45, in _ cdata = function(*args, **kwargs)

File "C:\Users\user\AppData\Local\conda\conda\envs\myenv\lib\site-packages\rpy2\rinterface.py", line 817, in call raise embedded.RRuntimeError(_rinterface._geterrmessage())

RRuntimeError: Error in loadNamespace(x) : object 'pkgInfo' not found

```
for row in rpy2.situation.iter_info()
      print(row)
```
rpy2 version: 3.5.8 Python version: 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)] Looking for R's HOME: Environment variable R_HOME: C:\Users\user\Documents\R\R-4.2.0 InstallPath in the registry: C:\Program Files\R\R-4.2.0 Environment variable R_USER: None Environment variable R_LIBS_USER: None Warning: The environment variable R_HOME differs from the default R in the PATH. R version: In the PATH: Loading R library from rpy2: OK Additional directories to load R packages from: None C extension compilation: include: ['C:/Users/user/Documents/R/R-4.2.0/include', 'C:/Users/user/Documents/R/R-4.2.0/include/x64'] libraries: ['R', 'm'] library_dirs: ['C:/Users/user/Documents/R/R-4.2.0/bin/x64'] extra_compile_args: ['-std=c99'] extra_link_args: [] Directory for the R shared library: lib

**Comment by EVanderSchel** [comment]
Reinstalled R and am no longer having the issue.
